import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import dotenv from "dotenv";
import { pool } from "./pool.js";

dotenv.config();

const __dirname = dirname(fileURLToPath(import.meta.url));

type RecipeSeed = {
  title: string;
  description: string;
  cuisine: string;
  cooking_time: number;
  servings: number;
  difficulty: string;
  instructions: string;
  ingredients: { name: string; quantity: number; unit: string }[];
  equipment: string[];
};

const recipes: RecipeSeed[] = [
  {
    title: "Tomato Egg Stir-Fry",
    description:
      "A classic home-style dish — silky scrambled eggs in a savory tomato sauce.",
    cuisine: "chinese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. Beat eggs with a pinch of salt.\n2. Dice tomatoes.\n3. Scramble eggs in oil, set aside.\n4. Sauté tomatoes until soft, add sugar and salt.\n5. Return eggs, toss and serve.",
    ingredients: [
      { name: "Eggs", quantity: 3, unit: "pieces" },
      { name: "Tomatoes", quantity: 2, unit: "pieces" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Sugar", quantity: 1, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Spinach Omelette",
    description: "A quick and nutritious omelette loaded with fresh spinach.",
    cuisine: "american",
    cooking_time: 10,
    servings: 1,
    difficulty: "easy",
    instructions:
      "1. Wilt spinach in a hot pan.\n2. Beat eggs with salt and pepper.\n3. Pour eggs over spinach.\n4. Cook until set, fold and serve.",
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Spinach", quantity: 100, unit: "g" },
      { name: "Salt", quantity: 0.25, unit: "tsp" },
      { name: "Butter", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Fried Rice",
    description: "Simple egg fried rice using leftover rice.",
    cuisine: "chinese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. Beat eggs.\n2. Heat oil, scramble eggs.\n3. Add rice, stir-fry on high heat.\n4. Season with soy sauce and salt.\n5. Add scallions and serve.",
    ingredients: [
      { name: "Rice", quantity: 300, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Salt", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Pasta Aglio e Olio",
    description:
      "Classic Italian garlic-and-oil pasta with chili flakes and parsley.",
    cuisine: "italian",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. Cook spaghetti in salted water until al dente.\n2. Sauté sliced garlic and chili in olive oil.\n3. Toss pasta into the pan with pasta water.\n4. Finish with parsley.",
    ingredients: [
      { name: "Spaghetti", quantity: 200, unit: "g" },
      { name: "Garlic", quantity: 4, unit: "pieces" },
      { name: "Olive Oil", quantity: 3, unit: "tbsp" },
      { name: "Chili Flakes", quantity: 0.5, unit: "tsp" },
      { name: "Parsley", quantity: 10, unit: "g" },
      { name: "Salt", quantity: 1, unit: "tsp" },
    ],
    equipment: ["湯鍋", "平底鍋"],
  },
  {
    title: "Miso Soup",
    description:
      "Light Japanese soup with tofu, wakame seaweed, and miso paste.",
    cuisine: "japanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. Bring dashi stock to a simmer.\n2. Add cubed tofu and wakame.\n3. Remove from heat, dissolve miso paste.\n4. Serve with sliced scallions.",
    ingredients: [
      { name: "Tofu", quantity: 150, unit: "g" },
      { name: "Miso Paste", quantity: 2, unit: "tbsp" },
      { name: "Wakame", quantity: 5, unit: "g" },
      { name: "Scallions", quantity: 1, unit: "pieces" },
      { name: "Dashi Stock", quantity: 500, unit: "ml" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Kimchi Fried Rice",
    description: "Spicy and savory fried rice with kimchi and a fried egg.",
    cuisine: "korean",
    cooking_time: 15,
    servings: 1,
    difficulty: "easy",
    instructions:
      "1. Stir-fry chopped kimchi in sesame oil.\n2. Add rice and kimchi juice, fry on high.\n3. Season with soy sauce.\n4. Top with a fried egg and sesame seeds.",
    ingredients: [
      { name: "Rice", quantity: 200, unit: "g" },
      { name: "Kimchi", quantity: 100, unit: "g" },
      { name: "Eggs", quantity: 1, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tbsp" },
      { name: "Sesame Seeds", quantity: 1, unit: "tsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Chicken Stir-Fry with Vegetables",
    description: "Quick weeknight stir-fry with chicken breast and veggies.",
    cuisine: "chinese",
    cooking_time: 20,
    servings: 2,
    difficulty: "medium",
    instructions:
      "1. Slice chicken breast, marinate with soy sauce and cornstarch.\n2. Stir-fry chicken until cooked, set aside.\n3. Stir-fry bell peppers, carrots, and broccoli.\n4. Return chicken, season and serve.",
    ingredients: [
      { name: "Chicken Breast", quantity: 250, unit: "g" },
      { name: "Bell Pepper", quantity: 1, unit: "pieces" },
      { name: "Carrots", quantity: 1, unit: "pieces" },
      { name: "Broccoli", quantity: 150, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Cornstarch", quantity: 1, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Thai Basil Pork",
    description:
      "Aromatic and spicy stir-fried pork with Thai basil over rice.",
    cuisine: "thai",
    cooking_time: 15,
    servings: 2,
    difficulty: "medium",
    instructions:
      "1. Mince pork or slice thinly.\n2. Fry garlic and chili in oil.\n3. Add pork, stir-fry until browned.\n4. Season with soy sauce, oyster sauce, and sugar.\n5. Toss in Thai basil leaves, serve over rice.",
    ingredients: [
      { name: "Pork", quantity: 200, unit: "g" },
      { name: "Thai Basil", quantity: 20, unit: "g" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Chili", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sugar", quantity: 1, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
      { name: "Rice", quantity: 300, unit: "g" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Creamy Mushroom Pasta",
    description: "Rich and comforting pasta with sautéed mushrooms in cream.",
    cuisine: "italian",
    cooking_time: 25,
    servings: 2,
    difficulty: "medium",
    instructions:
      "1. Cook penne in salted water.\n2. Sauté sliced mushrooms with garlic in butter.\n3. Add cream and parmesan, simmer.\n4. Toss with pasta and season.",
    ingredients: [
      { name: "Penne", quantity: 200, unit: "g" },
      { name: "Mushrooms", quantity: 200, unit: "g" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
      { name: "Butter", quantity: 2, unit: "tbsp" },
      { name: "Heavy Cream", quantity: 100, unit: "ml" },
      { name: "Parmesan", quantity: 30, unit: "g" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
    ],
    equipment: ["湯鍋", "平底鍋"],
  },
  {
    title: "Japanese Curry Rice",
    description:
      "Hearty Japanese-style curry with potatoes, carrots, and onions.",
    cuisine: "japanese",
    cooking_time: 45,
    servings: 4,
    difficulty: "medium",
    instructions:
      "1. Cut chicken, potatoes, carrots, and onions into chunks.\n2. Brown chicken in oil, add onions.\n3. Add water, potatoes, and carrots. Simmer 20 min.\n4. Add curry roux blocks, stir until thickened.\n5. Serve over steamed rice.",
    ingredients: [
      { name: "Chicken Thigh", quantity: 300, unit: "g" },
      { name: "Potatoes", quantity: 2, unit: "pieces" },
      { name: "Carrots", quantity: 1, unit: "pieces" },
      { name: "Onion", quantity: 1, unit: "pieces" },
      { name: "Curry Roux", quantity: 100, unit: "g" },
      { name: "Rice", quantity: 400, unit: "g" },
      { name: "Cooking Oil", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "Taiwanese Three-Cup Chicken",
    description:
      "Fragrant braised chicken with sesame oil, soy sauce, and rice wine.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions:
      "1. Cut chicken into pieces.\n2. Sear chicken in sesame oil.\n3. Add sliced ginger and garlic, fry until fragrant.\n4. Add soy sauce, rice wine, and sugar.\n5. Braise until sauce reduces.\n6. Add Thai basil, toss and serve.",
    ingredients: [
      { name: "Chicken Thigh", quantity: 400, unit: "g" },
      { name: "Sesame Oil", quantity: 3, unit: "tbsp" },
      { name: "Soy Sauce", quantity: 3, unit: "tbsp" },
      { name: "Rice Wine", quantity: 3, unit: "tbsp" },
      { name: "Ginger", quantity: 30, unit: "g" },
      { name: "Garlic", quantity: 6, unit: "pieces" },
      { name: "Thai Basil", quantity: 15, unit: "g" },
      { name: "Sugar", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Milk French Toast",
    description: "Golden pan-fried bread soaked in an egg-milk mixture.",
    cuisine: "american",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. Whisk eggs, milk, sugar, and vanilla.\n2. Dip bread slices in the mixture.\n3. Pan-fry in butter until golden on both sides.\n4. Serve with maple syrup or honey.",
    ingredients: [
      { name: "Bread", quantity: 4, unit: "pieces" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Milk", quantity: 100, unit: "ml" },
      { name: "Sugar", quantity: 1, unit: "tbsp" },
      { name: "Butter", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  // ── 台式料理 50 道 ──────────────────────────────────────────
  {
    title: "Braised Pork Rice",
    description: "Iconic Taiwanese street food — melt-in-your-mouth braised pork belly served over steamed white rice.",
    cuisine: "taiwanese",
    cooking_time: 60,
    servings: 4,
    difficulty: "medium",
    instructions: "1. Cut pork belly into small cubes.\n2. Fry shallots in oil until crispy golden, remove and set aside.\n3. Brown pork belly in the same oil.\n4. Add soy sauce, rice wine, sugar, and five-spice powder.\n5. Add water to just cover the pork, simmer on low heat 40 minutes.\n6. Add fried shallots, continue simmering 10 minutes until sauce thickens.\n7. Serve over steamed rice.",
    ingredients: [
      { name: "Pork Belly", quantity: 400, unit: "g" },
      { name: "Shallots", quantity: 5, unit: "pieces" },
      { name: "Soy Sauce", quantity: 4, unit: "tbsp" },
      { name: "Rice Wine", quantity: 3, unit: "tbsp" },
      { name: "Sugar", quantity: 1, unit: "tbsp" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Rice", quantity: 400, unit: "g" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋", "湯鍋", "電鍋"],
  },
  {
    title: "Sesame Oil Chicken",
    description: "A warming Taiwanese classic — tender chicken simmered in aromatic sesame oil and rice wine.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Cut chicken thighs into pieces.\n2. Heat sesame oil in a wok.\n3. Fry sliced ginger until fragrant and slightly crispy.\n4. Add chicken, sear until golden.\n5. Pour in rice wine, bring to a boil.\n6. Add soy sauce, cover and simmer 20 minutes.\n7. Serve hot.",
    ingredients: [
      { name: "Chicken Thigh", quantity: 500, unit: "g" },
      { name: "Sesame Oil", quantity: 3, unit: "tbsp" },
      { name: "Ginger", quantity: 50, unit: "g" },
      { name: "Rice Wine", quantity: 200, unit: "ml" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Beef Noodle Soup",
    description: "Taiwan's most beloved noodle dish — braised beef shank in a rich, spiced broth.",
    cuisine: "taiwanese",
    cooking_time: 120,
    servings: 4,
    difficulty: "hard",
    instructions: "1. Blanch beef shank in boiling water, rinse and cut into chunks.\n2. Sauté garlic and ginger in oil, add doubanjiang.\n3. Add beef, soy sauce, rice wine, star anise, and water to cover.\n4. Bring to a boil, skim foam, simmer 90 minutes until tender.\n5. Cook noodles separately.\n6. Serve broth and beef over noodles, garnish with scallions.",
    ingredients: [
      { name: "Beef Shank", quantity: 600, unit: "g" },
      { name: "Noodles", quantity: 400, unit: "g" },
      { name: "Doubanjiang", quantity: 2, unit: "tbsp" },
      { name: "Soy Sauce", quantity: 4, unit: "tbsp" },
      { name: "Rice Wine", quantity: 3, unit: "tbsp" },
      { name: "Garlic", quantity: 4, unit: "pieces" },
      { name: "Ginger", quantity: 30, unit: "g" },
      { name: "Scallions", quantity: 3, unit: "pieces" },
      { name: "Star Anise", quantity: 2, unit: "pieces" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
  {
    title: "Oyster Omelette",
    description: "A beloved Taiwanese night market dish — chewy sweet potato starch omelette loaded with fresh oysters.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Mix sweet potato starch with water to form a thin batter.\n2. Heat oil in a pan, add oysters and cook briefly.\n3. Pour batter over oysters, cook until set on the bottom.\n4. Beat eggs and pour over, scramble lightly.\n5. Flip carefully, cook through.\n6. Drizzle with oyster sauce and serve.",
    ingredients: [
      { name: "Oysters", quantity: 150, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Sweet Potato Starch", quantity: 3, unit: "tbsp" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Stir-Fried Rice Noodles",
    description: "Smoky wok-tossed rice noodles with pork and vegetables — a Taiwanese lunchtime staple.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Soak rice noodles in warm water until soft, drain.\n2. Julienne pork, cabbage, and carrots.\n3. Stir-fry pork in hot oil until cooked.\n4. Add cabbage and carrots, toss on high heat.\n5. Add noodles, soy sauce, and a splash of water.\n6. Toss until combined and slightly charred, add scallions and serve.",
    ingredients: [
      { name: "Rice Noodles", quantity: 200, unit: "g" },
      { name: "Pork", quantity: 150, unit: "g" },
      { name: "Cabbage", quantity: 100, unit: "g" },
      { name: "Carrots", quantity: 1, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Scallion Oil Chicken",
    description: "Simple yet elegant poached chicken drenched in fragrant scallion oil.",
    cuisine: "taiwanese",
    cooking_time: 35,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Bring a pot of water to a boil with ginger slices.\n2. Submerge chicken thighs, simmer 20 minutes until just cooked.\n3. Remove chicken, cool in ice water for 5 minutes, then slice.\n4. Heat oil until very hot, pour over sliced scallions — they will sizzle.\n5. Drizzle hot scallion oil over sliced chicken.\n6. Season with soy sauce and serve.",
    ingredients: [
      { name: "Chicken Thigh", quantity: 500, unit: "g" },
      { name: "Scallions", quantity: 4, unit: "pieces" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
  {
    title: "Hakka Stir-Fry",
    description: "A robust Hakka-style stir-fry with pork, dried squid, tofu, and leeks — bold and umami-packed.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 3,
    difficulty: "medium",
    instructions: "1. Cut pork belly, dried squid, and tofu into strips.\n2. Fry tofu strips in oil until golden, set aside.\n3. Stir-fry pork belly until fat renders and edges are crispy.\n4. Add dried squid and leeks, toss on high heat.\n5. Return tofu, season with soy sauce and oyster sauce.\n6. Finish with a splash of rice wine and serve.",
    ingredients: [
      { name: "Pork Belly", quantity: 150, unit: "g" },
      { name: "Dried Squid", quantity: 50, unit: "g" },
      { name: "Tofu", quantity: 200, unit: "g" },
      { name: "Leeks", quantity: 100, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Sweet and Sour Pork Ribs",
    description: "Tender pork ribs glazed in a tangy-sweet sauce — a perennial Taiwanese family favorite.",
    cuisine: "taiwanese",
    cooking_time: 45,
    servings: 3,
    difficulty: "medium",
    instructions: "1. Chop ribs into 4 cm pieces, blanch in boiling water.\n2. Pan-fry ribs in oil until golden.\n3. In a wok, combine rice vinegar, sugar, soy sauce, and ketchup.\n4. Bring to a boil, add ribs and toss to coat.\n5. Simmer until sauce thickens and clings to the ribs.\n6. Garnish with sesame seeds and serve.",
    ingredients: [
      { name: "Pork Ribs", quantity: 500, unit: "g" },
      { name: "Rice Vinegar", quantity: 3, unit: "tbsp" },
      { name: "Sugar", quantity: 3, unit: "tbsp" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Ketchup", quantity: 2, unit: "tbsp" },
      { name: "Cornstarch", quantity: 2, unit: "tbsp" },
      { name: "Sesame Seeds", quantity: 1, unit: "tsp" },
      { name: "Cooking Oil", quantity: 3, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Red-Braised Pork Belly",
    description: "Melt-tender pork belly slow-braised in soy sauce, sugar, and spices until glossy.",
    cuisine: "taiwanese",
    cooking_time: 90,
    servings: 4,
    difficulty: "medium",
    instructions: "1. Cut pork belly into large cubes, blanch 5 minutes and drain.\n2. In a pot, heat sugar until it caramelizes, add pork belly and toss.\n3. Add soy sauce, rice wine, five-spice, ginger, and water to cover.\n4. Simmer covered 60–70 minutes until tender.\n5. Remove lid and reduce sauce until thick and glossy.",
    ingredients: [
      { name: "Pork Belly", quantity: 600, unit: "g" },
      { name: "Soy Sauce", quantity: 4, unit: "tbsp" },
      { name: "Rice Wine", quantity: 3, unit: "tbsp" },
      { name: "Sugar", quantity: 2, unit: "tbsp" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Steamed Fish with Soy Sauce",
    description: "Light and fresh whole steamed fish finished with a sizzle of hot scallion oil.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Score both sides of the fish.\n2. Place ginger slices inside and on top.\n3. Steam fish over high heat for 10–12 minutes.\n4. Discard excess liquid, drizzle with soy sauce.\n5. Top with shredded scallions.\n6. Heat oil until smoking hot, pour over scallions to release aroma.\n7. Serve immediately.",
    ingredients: [
      { name: "Sea Bass", quantity: 1, unit: "pieces" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Scallions", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
      { name: "Sugar", quantity: 0.5, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Garlic Stir-Fried Water Spinach",
    description: "A quick and smoky wok-tossed water spinach with garlic — a must-order at Taiwanese restaurants.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Trim water spinach, wash and dry well.\n2. Smash garlic cloves.\n3. Heat wok until very hot, add oil.\n4. Add garlic, stir-fry until fragrant.\n5. Add water spinach, toss rapidly on high heat.\n6. Season with salt and oyster sauce, serve immediately.",
    ingredients: [
      { name: "Water Spinach", quantity: 300, unit: "g" },
      { name: "Garlic", quantity: 4, unit: "pieces" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Dried Radish Omelette",
    description: "A homey Taiwanese omelette with salty, savory preserved radish — perfect with rice.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Rinse dried radish to remove excess salt, chop finely.\n2. Beat eggs with a pinch of white pepper.\n3. Heat oil in a pan, stir-fry radish for 1 minute.\n4. Pour beaten eggs over radish.\n5. Cook undisturbed until edges set, then fold.\n6. Flip and cook until golden. Serve.",
    ingredients: [
      { name: "Eggs", quantity: 3, unit: "pieces" },
      { name: "Dried Radish", quantity: 40, unit: "g" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Pork Rib Soup",
    description: "A clear, nourishing Taiwanese soup with tender pork ribs — simple and deeply comforting.",
    cuisine: "taiwanese",
    cooking_time: 50,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Blanch pork ribs in boiling water, rinse clean.\n2. Place ribs in a pot with ginger and enough water to cover.\n3. Bring to a boil, skim foam, then simmer 35 minutes.\n4. Add daikon radish, simmer another 10 minutes.\n5. Season with salt and white pepper.\n6. Garnish with scallions and serve.",
    ingredients: [
      { name: "Pork Ribs", quantity: 400, unit: "g" },
      { name: "Daikon Radish", quantity: 200, unit: "g" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Bitter Melon Pork Rib Soup",
    description: "A cooling, slightly bitter soup prized in Taiwanese households for its health benefits.",
    cuisine: "taiwanese",
    cooking_time: 50,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Blanch pork ribs in boiling water, drain.\n2. Halve bitter melon lengthwise, scrape out seeds, cut into chunks.\n3. Place ribs, bitter melon, and ginger in a pot with water.\n4. Bring to a boil, simmer 40 minutes.\n5. Season with salt and serve.",
    ingredients: [
      { name: "Pork Ribs", quantity: 400, unit: "g" },
      { name: "Bitter Melon", quantity: 1, unit: "pieces" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Salt", quantity: 1, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Braised Tofu",
    description: "Pan-fried tofu braised in a savory soy sauce — hearty and satisfying.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Cut tofu into thick slices, pat dry.\n2. Pan-fry tofu in oil until golden on both sides, set aside.\n3. Sauté garlic in the same pan.\n4. Add soy sauce, oyster sauce, sugar, and a splash of water.\n5. Return tofu, simmer until sauce thickens.\n6. Garnish with scallions and serve.",
    ingredients: [
      { name: "Tofu", quantity: 300, unit: "g" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sugar", quantity: 0.5, unit: "tsp" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Cooking Oil", quantity: 3, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Garlic Stir-Fried Cabbage",
    description: "Simple wok-tossed cabbage with garlic — a staple side dish at every Taiwanese table.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Tear or chop cabbage into large pieces.\n2. Smash garlic cloves.\n3. Heat wok with oil on high heat.\n4. Add garlic, fry until fragrant.\n5. Add cabbage, toss rapidly.\n6. Season with salt and a little oyster sauce. Serve immediately.",
    ingredients: [
      { name: "Cabbage", quantity: 400, unit: "g" },
      { name: "Garlic", quantity: 4, unit: "pieces" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Taiwanese Fried Pork Chop",
    description: "Crispy deep-fried pork chop marinated in soy sauce and five-spice — a beloved lunchbox staple.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Tenderize pork chops by pounding lightly.\n2. Marinate in soy sauce, rice wine, and five-spice for 20 minutes.\n3. Coat with sweet potato starch.\n4. Deep-fry in oil at 180°C for 4–5 minutes until golden.\n5. Rest for 2 minutes and serve with rice.",
    ingredients: [
      { name: "Pork Chop", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Sweet Potato Starch", quantity: 4, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 400, unit: "ml" },
      { name: "Rice", quantity: 300, unit: "g" },
    ],
    equipment: ["炒鍋", "電鍋"],
  },
  {
    title: "Oyster Vermicelli Soup",
    description: "A thick, comforting Taiwanese street soup with oysters and sweet potato vermicelli.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions: "1. Soak sweet potato vermicelli until soft.\n2. Bring broth to a boil, add oysters and cook 2 minutes.\n3. Add vermicelli, simmer 3 minutes.\n4. Stir in sweet potato starch dissolved in water to thicken.\n5. Season with soy sauce and white pepper.\n6. Drizzle with sesame oil and garnish with cilantro.",
    ingredients: [
      { name: "Oysters", quantity: 150, unit: "g" },
      { name: "Sweet Potato Vermicelli", quantity: 100, unit: "g" },
      { name: "Sweet Potato Starch", quantity: 3, unit: "tbsp" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
      { name: "Cilantro", quantity: 10, unit: "g" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Garlic Sweet Potato Leaves",
    description: "Quick stir-fried sweet potato leaves with garlic — a nutritious everyday Taiwanese vegetable dish.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Trim sweet potato leaves and wash thoroughly.\n2. Smash garlic cloves.\n3. Heat oil in a wok over high heat.\n4. Fry garlic until fragrant.\n5. Add sweet potato leaves, toss rapidly.\n6. Season with salt, stir-fry 2 minutes and serve.",
    ingredients: [
      { name: "Sweet Potato Leaves", quantity: 300, unit: "g" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Steamed Egg Custard",
    description: "Silky smooth steamed egg — simple, comforting, and deeply satisfying.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Beat eggs until smooth.\n2. Mix in lukewarm water at a 1:1.5 egg-to-liquid ratio.\n3. Add a pinch of salt and a few drops of soy sauce.\n4. Strain through a sieve into a bowl.\n5. Cover with plastic wrap, steam on low heat 12 minutes.\n6. Drizzle with soy sauce and sesame oil to serve.",
    ingredients: [
      { name: "Eggs", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 0.5, unit: "tsp" },
      { name: "Salt", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Stir-Fried Bean Sprouts",
    description: "Crisp and fresh stir-fried bean sprouts with garlic and scallions — ready in minutes.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Rinse and drain bean sprouts.\n2. Mince garlic, slice scallions.\n3. Heat wok over high heat with oil.\n4. Add garlic, fry briefly.\n5. Add bean sprouts, toss rapidly for 2 minutes.\n6. Season with salt and a splash of rice wine. Serve immediately.",
    ingredients: [
      { name: "Bean Sprouts", quantity: 300, unit: "g" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Winter Melon Clam Soup",
    description: "A delicate, light soup with sweet clams and tender winter melon — refreshing and clean.",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Soak clams in salted water to purge sand, then rinse.\n2. Cut winter melon into chunks.\n3. Bring water to a boil with ginger slices.\n4. Add winter melon, cook 10 minutes until translucent.\n5. Add clams, cook until they open, about 3 minutes.\n6. Season with salt and serve.",
    ingredients: [
      { name: "Clams", quantity: 300, unit: "g" },
      { name: "Winter Melon", quantity: 300, unit: "g" },
      { name: "Ginger", quantity: 15, unit: "g" },
      { name: "Salt", quantity: 0.75, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Stir-Fried Eggplant",
    description: "Silky, deeply flavored eggplant braised with garlic, soy sauce, and oyster sauce.",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Cut eggplant into strips, sprinkle with salt and rest 10 minutes.\n2. Pat eggplant dry.\n3. Pan-fry eggplant in oil until soft and browned, set aside.\n4. Sauté garlic in the pan.\n5. Return eggplant, add soy sauce, oyster sauce, and a little sugar.\n6. Toss to coat, serve hot.",
    ingredients: [
      { name: "Eggplant", quantity: 2, unit: "pieces" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sugar", quantity: 0.5, unit: "tsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 3, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Lotus Root Pork Rib Soup",
    description: "A nourishing soup with crunchy lotus root and fall-off-the-bone pork ribs.",
    cuisine: "taiwanese",
    cooking_time: 70,
    servings: 4,
    difficulty: "easy",
    instructions: "1. Blanch pork ribs in boiling water, drain.\n2. Peel lotus root and cut into thick rounds.\n3. Place ribs, lotus root, and ginger in a pot with water.\n4. Bring to a boil, skim foam, simmer 60 minutes.\n5. Season with salt and white pepper, serve.",
    ingredients: [
      { name: "Pork Ribs", quantity: 400, unit: "g" },
      { name: "Lotus Root", quantity: 300, unit: "g" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Salt", quantity: 1, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Steamed Minced Pork Patty",
    description: "A tender, homey Taiwanese steamed dish — seasoned minced pork steamed until juicy.",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Combine ground pork with soy sauce, sesame oil, rice wine, and cornstarch.\n2. Add minced ginger and scallions, mix well.\n3. Press into a shallow bowl.\n4. Steam over medium-high heat for 18–20 minutes.\n5. Drizzle with extra soy sauce and serve over rice.",
    ingredients: [
      { name: "Ground Pork", quantity: 250, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Cornstarch", quantity: 1, unit: "tsp" },
      { name: "Ginger", quantity: 10, unit: "g" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Rice", quantity: 300, unit: "g" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "Taro Pork Rib Soup",
    description: "A creamy, fragrant soup with soft taro and savory pork ribs.",
    cuisine: "taiwanese",
    cooking_time: 50,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Blanch pork ribs, drain.\n2. Peel taro, cut into large chunks.\n3. Place ribs, taro, and ginger in a pot, add water.\n4. Bring to a boil, simmer 35–40 minutes until taro is very soft.\n5. Season with salt. The taro will naturally thicken the broth.",
    ingredients: [
      { name: "Pork Ribs", quantity: 400, unit: "g" },
      { name: "Taro", quantity: 300, unit: "g" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Salt", quantity: 1, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Taiwanese Savory Congee",
    description: "A comforting thin rice porridge topped with pork, scallions, and crispy shallots.",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Simmer rice with plenty of water for 30 minutes into a loose porridge.\n2. Stir-fry ground pork with soy sauce until cooked.\n3. Add pork to the congee, stir.\n4. Season with salt and white pepper.\n5. Serve topped with scallions, fried shallots, and a drizzle of sesame oil.",
    ingredients: [
      { name: "Rice", quantity: 150, unit: "g" },
      { name: "Ground Pork", quantity: 100, unit: "g" },
      { name: "Shallots", quantity: 3, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Shrimp and Egg Stir-Fry",
    description: "Tender shrimp tossed with silky scrambled eggs — a simple and elegant Taiwanese classic.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Peel and devein shrimp, season with salt and a little rice wine.\n2. Beat eggs with salt.\n3. Scramble eggs in hot oil until just set, remove.\n4. Stir-fry shrimp in the same pan until pink.\n5. Return eggs, toss gently to combine.\n6. Garnish with scallions and serve.",
    ingredients: [
      { name: "Shrimp", quantity: 200, unit: "g" },
      { name: "Eggs", quantity: 3, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Pork with Garlic Shoots",
    description: "Savory stir-fried pork slices with fragrant garlic shoots — a Taiwanese home-cooking classic.",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Slice pork thinly, marinate with soy sauce and cornstarch.\n2. Slice garlic shoots diagonally.\n3. Stir-fry pork in hot oil until just cooked, set aside.\n4. Stir-fry garlic shoots until tender.\n5. Return pork, season with oyster sauce and a splash of rice wine.\n6. Toss and serve.",
    ingredients: [
      { name: "Pork", quantity: 200, unit: "g" },
      { name: "Garlic Shoots", quantity: 150, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Cornstarch", quantity: 1, unit: "tsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Century Egg Tofu",
    description: "A no-cook Taiwanese classic — silky cold tofu topped with century egg and scallion oil.",
    cuisine: "taiwanese",
    cooking_time: 5,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Slice silken tofu and arrange on a plate.\n2. Dice century eggs and scatter over tofu.\n3. Heat oil until hot, pour over thinly sliced scallions.\n4. Drizzle soy sauce and scallion oil over the dish.\n5. Sprinkle with sesame seeds and serve immediately.",
    ingredients: [
      { name: "Silken Tofu", quantity: 300, unit: "g" },
      { name: "Century Egg", quantity: 2, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Sesame Seeds", quantity: 1, unit: "tsp" },
      { name: "Cooking Oil", quantity: 1, unit: "tbsp" },
    ],
    equipment: [],
  },
  {
    title: "Garlic White Pork",
    description: "Thinly sliced poached pork belly drizzled with garlicky soy sauce — refreshing and addictive.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions: "1. Simmer pork belly whole with ginger and rice wine for 20 minutes.\n2. Cool completely, then slice thinly.\n3. Arrange on a plate with sliced cucumbers.\n4. Mix minced garlic, soy sauce, sesame oil, and rice vinegar.\n5. Pour dressing over pork slices.\n6. Garnish with scallions.",
    ingredients: [
      { name: "Pork Belly", quantity: 400, unit: "g" },
      { name: "Garlic", quantity: 5, unit: "pieces" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Soy Sauce", quantity: 3, unit: "tbsp" },
      { name: "Rice Wine", quantity: 2, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tbsp" },
      { name: "Rice Vinegar", quantity: 1, unit: "tbsp" },
      { name: "Cucumbers", quantity: 1, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Taiwanese Stir-Fried Noodles",
    description: "Smoky wok-fried noodles with pork, cabbage, and a savory soy-based sauce.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Cook noodles until just tender, drain and toss with a little oil.\n2. Julienne pork and cabbage.\n3. Stir-fry pork in hot oil until cooked.\n4. Add cabbage, toss on high heat.\n5. Add noodles, soy sauce, oyster sauce, and white pepper.\n6. Toss everything together until well combined and serve.",
    ingredients: [
      { name: "Noodles", quantity: 200, unit: "g" },
      { name: "Pork", quantity: 150, unit: "g" },
      { name: "Cabbage", quantity: 150, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋", "湯鍋"],
  },
  {
    title: "Stuffed Bitter Melon",
    description: "Bitter melon rings stuffed with seasoned minced pork and braised in savory sauce.",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 3,
    difficulty: "medium",
    instructions: "1. Cut bitter melon into thick rings, scoop out seeds.\n2. Mix ground pork with soy sauce, sesame oil, ginger, and cornstarch.\n3. Stuff pork mixture into each ring.\n4. Pan-fry stuffed rings until golden on each side.\n5. Add a little water, soy sauce, and oyster sauce.\n6. Cover and braise 15 minutes until pork is cooked through.",
    ingredients: [
      { name: "Bitter Melon", quantity: 1, unit: "pieces" },
      { name: "Ground Pork", quantity: 250, unit: "g" },
      { name: "Soy Sauce", quantity: 3, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Ginger", quantity: 10, unit: "g" },
      { name: "Cornstarch", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Pork Ball Soup",
    description: "A warming clear soup with bouncy Taiwanese pork balls and cabbage.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Bring broth to a gentle simmer.\n2. Add pork balls, simmer 5 minutes.\n3. Add cabbage, cook 3 more minutes.\n4. Season with salt and white pepper.\n5. Garnish with scallions and a drizzle of sesame oil.",
    ingredients: [
      { name: "Pork Balls", quantity: 200, unit: "g" },
      { name: "Cabbage", quantity: 150, unit: "g" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Salt", quantity: 0.75, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Steamed Ribs with Black Bean Sauce",
    description: "Tender pork ribs marinated in fermented black bean sauce and steamed to perfection.",
    cuisine: "taiwanese",
    cooking_time: 35,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Chop ribs into small pieces, rinse and pat dry.\n2. Marinate with fermented black beans, garlic, soy sauce, sesame oil, sugar, and cornstarch for 20 minutes.\n3. Spread on a plate, steam over boiling water.\n4. Steam on high heat for 20–25 minutes until cooked through.\n5. Garnish with chopped scallions and serve with rice.",
    ingredients: [
      { name: "Pork Ribs", quantity: 400, unit: "g" },
      { name: "Fermented Black Beans", quantity: 2, unit: "tbsp" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Sugar", quantity: 0.5, unit: "tsp" },
      { name: "Cornstarch", quantity: 1, unit: "tbsp" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Rice", quantity: 300, unit: "g" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "Taiwanese Fried Chicken Cutlet",
    description: "Juicy, crispy large chicken breast — the iconic Taiwanese night market snack.",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Butterfly chicken breast to an even thickness.\n2. Marinate in soy sauce, rice wine, garlic, and five-spice for 30 minutes.\n3. Coat generously with sweet potato starch.\n4. Deep-fry at 175°C for 5–6 minutes until golden and cooked.\n5. Drain excess oil, serve with briefly fried basil leaves.",
    ingredients: [
      { name: "Chicken Breast", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Sweet Potato Starch", quantity: 5, unit: "tbsp" },
      { name: "Thai Basil", quantity: 10, unit: "g" },
      { name: "Cooking Oil", quantity: 400, unit: "ml" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Braised Pork Knuckle",
    description: "Fall-off-the-bone pork knuckle slow-braised in a rich soy and five-spice sauce.",
    cuisine: "taiwanese",
    cooking_time: 120,
    servings: 4,
    difficulty: "hard",
    instructions: "1. Blanch pork knuckle in boiling water for 5 minutes, rinse.\n2. Caramelize sugar in a large pot, add pork knuckle and toss.\n3. Add soy sauce, rice wine, five-spice, star anise, ginger, and water to cover.\n4. Bring to a boil, reduce heat and simmer 90 minutes, turning occasionally.\n5. Increase heat to reduce sauce. Serve with rice.",
    ingredients: [
      { name: "Pork Knuckle", quantity: 1, unit: "pieces" },
      { name: "Soy Sauce", quantity: 5, unit: "tbsp" },
      { name: "Rice Wine", quantity: 4, unit: "tbsp" },
      { name: "Sugar", quantity: 2, unit: "tbsp" },
      { name: "Five-Spice Powder", quantity: 1, unit: "tsp" },
      { name: "Star Anise", quantity: 3, unit: "pieces" },
      { name: "Ginger", quantity: 30, unit: "g" },
      { name: "Scallions", quantity: 3, unit: "pieces" },
      { name: "Rice", quantity: 400, unit: "g" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "Home-Style Tofu",
    description: "Pan-fried tofu with pork, scallions, and a savory sauce — a comforting Taiwanese staple.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Cut tofu into cubes, pan-fry until golden on all sides.\n2. Stir-fry minced pork until cooked.\n3. Add garlic, toss briefly.\n4. Return tofu, add soy sauce, oyster sauce, and a little water.\n5. Simmer 3 minutes, finish with sesame oil.\n6. Top with scallions and serve.",
    ingredients: [
      { name: "Tofu", quantity: 300, unit: "g" },
      { name: "Ground Pork", quantity: 100, unit: "g" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 0.5, unit: "tsp" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Cooking Oil", quantity: 3, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Ginger Duck Stew",
    description: "A warming and restorative Taiwanese dish — duck slow-simmered with old ginger and sesame oil.",
    cuisine: "taiwanese",
    cooking_time: 60,
    servings: 4,
    difficulty: "medium",
    instructions: "1. Rinse and cut duck into pieces.\n2. Heat sesame oil in a pot, fry sliced ginger until fragrant and golden.\n3. Add duck pieces, sear until browned.\n4. Pour in rice wine and a little water.\n5. Add soy sauce, cover and simmer 45 minutes until duck is tender.\n6. Adjust seasoning and serve.",
    ingredients: [
      { name: "Duck", quantity: 600, unit: "g" },
      { name: "Ginger", quantity: 80, unit: "g" },
      { name: "Sesame Oil", quantity: 3, unit: "tbsp" },
      { name: "Rice Wine", quantity: 200, unit: "ml" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Pork Chop Noodle Soup",
    description: "Crispy fried pork chop served over noodles in a clear, savory broth.",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Marinate pork chops in soy sauce, rice wine, and five-spice for 20 minutes.\n2. Coat with sweet potato starch, deep-fry at 180°C until golden.\n3. Simmer broth with ginger and scallions, season with soy sauce.\n4. Cook noodles, drain and place in bowls.\n5. Pour hot broth over noodles.\n6. Slice pork chop on top, garnish with scallions.",
    ingredients: [
      { name: "Pork Chop", quantity: 2, unit: "pieces" },
      { name: "Noodles", quantity: 200, unit: "g" },
      { name: "Soy Sauce", quantity: 3, unit: "tbsp" },
      { name: "Rice Wine", quantity: 2, unit: "tbsp" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Sweet Potato Starch", quantity: 4, unit: "tbsp" },
      { name: "Ginger", quantity: 15, unit: "g" },
      { name: "Scallions", quantity: 3, unit: "pieces" },
      { name: "Cooking Oil", quantity: 400, unit: "ml" },
    ],
    equipment: ["炒鍋", "湯鍋"],
  },
  {
    title: "Stir-Fried Asparagus with Shrimp",
    description: "Fresh asparagus stir-fried with juicy shrimp — light, healthy, and vibrant.",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Trim asparagus, cut diagonally into pieces.\n2. Peel and devein shrimp.\n3. Stir-fry shrimp in hot oil until pink, set aside.\n4. Stir-fry asparagus with garlic until tender-crisp.\n5. Return shrimp, season with salt and oyster sauce.\n6. Finish with a splash of rice wine and serve.",
    ingredients: [
      { name: "Asparagus", quantity: 200, unit: "g" },
      { name: "Shrimp", quantity: 150, unit: "g" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Taiwanese Popcorn Chicken",
    description: "Addictive crispy fried chicken bites with basil — a beloved Taiwanese street food.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions: "1. Cut chicken thighs into bite-size pieces.\n2. Marinate with soy sauce, rice wine, garlic, and five-spice for 20 minutes.\n3. Coat with sweet potato starch.\n4. Deep-fry at 175°C until golden and crispy.\n5. In the last minute, add fresh basil leaves to the oil briefly.\n6. Drain and season with white pepper.",
    ingredients: [
      { name: "Chicken Thigh", quantity: 400, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "Rice Wine", quantity: 1, unit: "tbsp" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Sweet Potato Starch", quantity: 5, unit: "tbsp" },
      { name: "Thai Basil", quantity: 15, unit: "g" },
      { name: "White Pepper", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 400, unit: "ml" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Braised Pork with Preserved Vegetables",
    description: "Melt-tender pork belly braised with salty preserved mustard greens — rich and deeply flavored.",
    cuisine: "taiwanese",
    cooking_time: 90,
    servings: 4,
    difficulty: "hard",
    instructions: "1. Rinse preserved mustard greens thoroughly, chop roughly.\n2. Slice pork belly into thick pieces.\n3. Fry shallots in oil until golden.\n4. Add pork belly, sear until browned.\n5. Add preserved greens, soy sauce, rice wine, and sugar.\n6. Add water to cover, simmer on low heat 70 minutes.\n7. Increase heat to reduce sauce before serving.",
    ingredients: [
      { name: "Pork Belly", quantity: 500, unit: "g" },
      { name: "Preserved Mustard Greens", quantity: 150, unit: "g" },
      { name: "Shallots", quantity: 4, unit: "pieces" },
      { name: "Soy Sauce", quantity: 4, unit: "tbsp" },
      { name: "Rice Wine", quantity: 3, unit: "tbsp" },
      { name: "Sugar", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
  {
    title: "Braised Eggs",
    description: "Savory, deeply flavored Taiwanese braised eggs simmered in soy sauce and five-spice.",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 4,
    difficulty: "easy",
    instructions: "1. Hard-boil eggs, peel, and score the surface lightly.\n2. Combine soy sauce, tea, five-spice, sugar, and water in a pot.\n3. Add eggs, bring to a boil, then simmer 25 minutes.\n4. Turn off heat, let eggs soak at least 10 minutes.\n5. Slice and serve warm or at room temperature.",
    ingredients: [
      { name: "Eggs", quantity: 6, unit: "pieces" },
      { name: "Soy Sauce", quantity: 4, unit: "tbsp" },
      { name: "Five-Spice Powder", quantity: 1, unit: "tsp" },
      { name: "Sugar", quantity: 1, unit: "tbsp" },
      { name: "Tea Bags", quantity: 2, unit: "pieces" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Taiwanese Egg Drop Soup",
    description: "A silky, light egg drop soup seasoned with white pepper and sesame oil.",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Bring broth to a boil, season with salt.\n2. Stir in cornstarch dissolved in water to slightly thicken.\n3. Beat eggs, slowly drizzle into simmering broth while stirring.\n4. Add tomato wedges.\n5. Season with white pepper, drizzle with sesame oil.\n6. Garnish with scallions and serve.",
    ingredients: [
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Tomatoes", quantity: 1, unit: "pieces" },
      { name: "Cornstarch", quantity: 1, unit: "tbsp" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Sesame Oil", quantity: 0.5, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
      { name: "Salt", quantity: 0.75, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Taiwanese Minced Pork Noodles",
    description: "Noodles topped with savory ground pork sauce and a soft-boiled egg — a Taiwanese lunchtime classic.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Cook noodles until tender, drain.\n2. Stir-fry ground pork until cooked through.\n3. Add soy sauce, rice wine, sugar, and five-spice, simmer 10 minutes.\n4. Add fried shallots, stir to combine.\n5. Pour meat sauce over noodles.\n6. Top with a soft-boiled egg and scallions.",
    ingredients: [
      { name: "Noodles", quantity: 200, unit: "g" },
      { name: "Ground Pork", quantity: 200, unit: "g" },
      { name: "Shallots", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 3, unit: "tbsp" },
      { name: "Rice Wine", quantity: 2, unit: "tbsp" },
      { name: "Sugar", quantity: 1, unit: "tsp" },
      { name: "Five-Spice Powder", quantity: 0.5, unit: "tsp" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Cooking Oil", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["炒鍋", "湯鍋"],
  },
  {
    title: "Simple Tofu Soup",
    description: "A clean, nourishing broth with soft tofu and vegetables — light and soothing.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Cut tofu into cubes.\n2. Bring broth to a boil with ginger slices.\n3. Add tofu and mushrooms, simmer 5 minutes.\n4. Add scallions.\n5. Season with salt, white pepper, and sesame oil.\n6. Serve hot.",
    ingredients: [
      { name: "Tofu", quantity: 300, unit: "g" },
      { name: "Mushrooms", quantity: 100, unit: "g" },
      { name: "Ginger", quantity: 10, unit: "g" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Sesame Oil", quantity: 0.5, unit: "tsp" },
      { name: "Salt", quantity: 0.75, unit: "tsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Stir-Fried Enoki Mushrooms",
    description: "Quick and savory stir-fried enoki mushrooms with garlic and scallions.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Trim enoki mushrooms, separate into small bunches.\n2. Mince garlic, slice scallions.\n3. Heat oil in a wok over medium-high heat.\n4. Fry garlic until fragrant.\n5. Add enoki mushrooms, toss on high heat 2 minutes.\n6. Season with soy sauce and oyster sauce, serve.",
    ingredients: [
      { name: "Enoki Mushrooms", quantity: 200, unit: "g" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
      { name: "Scallions", quantity: 2, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Braised Chicken Wings",
    description: "Tender chicken wings braised in soy sauce, rice wine, and ginger — sticky and flavorful.",
    cuisine: "taiwanese",
    cooking_time: 35,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Rinse chicken wings and pat dry.\n2. Brown wings in oil on all sides.\n3. Add garlic and ginger, fry briefly.\n4. Add soy sauce, rice wine, sugar, and water to half cover.\n5. Simmer 25 minutes, turning wings halfway.\n6. Increase heat to reduce sauce. Serve.",
    ingredients: [
      { name: "Chicken Wings", quantity: 500, unit: "g" },
      { name: "Soy Sauce", quantity: 3, unit: "tbsp" },
      { name: "Rice Wine", quantity: 2, unit: "tbsp" },
      { name: "Sugar", quantity: 1, unit: "tbsp" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Ginger", quantity: 15, unit: "g" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Scallion Pancake",
    description: "Flaky, layered pan-fried flatbread with fragrant scallions — a beloved Taiwanese breakfast.",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Mix flour, boiling water, and a pinch of salt into a smooth dough, rest 20 minutes.\n2. Roll out thin, brush with oil, and scatter chopped scallions.\n3. Roll up tightly into a log, then coil into a disc.\n4. Flatten again with a rolling pin.\n5. Pan-fry in oil over medium heat until golden and flaky on both sides.",
    ingredients: [
      { name: "All-Purpose Flour", quantity: 200, unit: "g" },
      { name: "Scallions", quantity: 4, unit: "pieces" },
      { name: "Cooking Oil", quantity: 3, unit: "tbsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "Stir-Fried Pork with Pickled Mustard Greens",
    description: "Salty, tangy pickled mustard greens stir-fried with pork — a powerful flavor combo.",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Rinse pickled mustard greens, squeeze dry, chop.\n2. Slice pork thinly, marinate with soy sauce and cornstarch.\n3. Stir-fry pork in hot oil until cooked, remove.\n4. Stir-fry mustard greens with garlic and chili.\n5. Return pork, toss together and serve over rice.",
    ingredients: [
      { name: "Pork", quantity: 200, unit: "g" },
      { name: "Pickled Mustard Greens", quantity: 150, unit: "g" },
      { name: "Garlic", quantity: 2, unit: "pieces" },
      { name: "Chili", quantity: 1, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Cornstarch", quantity: 1, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Tofu and Vegetable Hot Pot",
    description: "A warming, simple hot pot with tofu, mushrooms, and vegetables in a light broth.",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 3,
    difficulty: "easy",
    instructions: "1. Bring broth to a boil with ginger.\n2. Add tofu, mushrooms, and cabbage.\n3. Simmer 10 minutes.\n4. Add spinach, cook 2 more minutes.\n5. Season with salt, soy sauce, and sesame oil.\n6. Serve directly from the pot.",
    ingredients: [
      { name: "Tofu", quantity: 300, unit: "g" },
      { name: "Mushrooms", quantity: 150, unit: "g" },
      { name: "Cabbage", quantity: 200, unit: "g" },
      { name: "Spinach", quantity: 100, unit: "g" },
      { name: "Ginger", quantity: 15, unit: "g" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 1, unit: "tsp" },
      { name: "Salt", quantity: 0.75, unit: "tsp" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "Stir-Fried Pork Liver",
    description: "Thinly sliced pork liver stir-fried with ginger and scallions — tender and iron-rich.",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Slice pork liver thinly, soak in water 10 minutes, then drain.\n2. Marinate with rice wine and soy sauce.\n3. Heat wok until very hot, add oil.\n4. Stir-fry ginger slices briefly.\n5. Add liver, stir-fry on high heat 2–3 minutes — do not overcook.\n6. Add scallions, oyster sauce, and sesame oil, toss and serve.",
    ingredients: [
      { name: "Pork Liver", quantity: 250, unit: "g" },
      { name: "Ginger", quantity: 20, unit: "g" },
      { name: "Scallions", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Rice Wine", quantity: 2, unit: "tbsp" },
      { name: "Oyster Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "Taiwanese Pineapple Fried Rice",
    description: "Tropical fried rice with shrimp, pineapple chunks, and cashews — sweet, savory, and satisfying.",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "medium",
    instructions: "1. Cook rice in advance and let it cool.\n2. Stir-fry shrimp in oil until pink, set aside.\n3. Scramble eggs in the same pan, add rice and stir-fry on high heat.\n4. Add pineapple chunks, cashews, and soy sauce.\n5. Return shrimp, season with salt and white pepper, serve.",
    ingredients: [
      { name: "Rice", quantity: 300, unit: "g" },
      { name: "Shrimp", quantity: 150, unit: "g" },
      { name: "Eggs", quantity: 2, unit: "pieces" },
      { name: "Pineapple", quantity: 150, unit: "g" },
      { name: "Cashews", quantity: 30, unit: "g" },
      { name: "Soy Sauce", quantity: 2, unit: "tbsp" },
      { name: "White Pepper", quantity: 0.25, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
    ],
    equipment: ["炒鍋", "電鍋"],
  },
  {
    title: "Spinach with Garlic Oil",
    description: "Blanched spinach dressed with garlic oil and soy sauce — a simple, healthy Taiwanese side.",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. Blanch spinach in boiling salted water for 1 minute.\n2. Drain and gently squeeze out excess water.\n3. Heat oil, fry minced garlic until golden.\n4. Drizzle garlic oil over spinach.\n5. Season with soy sauce and sesame oil, toss and serve.",
    ingredients: [
      { name: "Spinach", quantity: 300, unit: "g" },
      { name: "Garlic", quantity: 3, unit: "pieces" },
      { name: "Soy Sauce", quantity: 1, unit: "tbsp" },
      { name: "Sesame Oil", quantity: 0.5, unit: "tsp" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp" },
      { name: "Salt", quantity: 0.5, unit: "tsp" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
];

async function seed() {
  const schema = readFileSync(join(__dirname, "schema.sql"), "utf-8");
  await pool.query(schema);

  /* ---- ingredients (existing MVP seed) ---- */
  await pool.query(`DELETE FROM ingredients WHERE user_id = 1`);

  await pool.query(
    `INSERT INTO ingredients (
       user_id, name, count_quantity, count_unit, measure_quantity, measure_unit,
       category, status, expiry_date
     )
     VALUES
       (1, 'Milk',      NULL, NULL, 1,   'L',  'dairy',     'opened', CURRENT_DATE + 2),
       (1, 'Eggs',      12,   '顆', NULL, NULL, 'dairy',     'fresh',  CURRENT_DATE + 10),
       (1, 'Spinach',   NULL, NULL, 200, 'g',  'vegetable', 'fresh',  CURRENT_DATE - 1),
       (1, 'Rice',      NULL, NULL, 500, 'g',  'grain',     'fresh',  NULL),
       (1, 'Soy Sauce', 1,    '包', NULL, NULL, 'condiment', 'opened', CURRENT_DATE + 90),
       (1, 'Garlic',    5,    '顆', NULL, NULL, 'vegetable', 'fresh',  CURRENT_DATE + 14),
       (1, 'Butter',    NULL, NULL, 100, 'g',  'dairy',     'fresh',  CURRENT_DATE + 30),
       (1, 'Tomatoes',  3,    '顆', NULL, NULL, 'vegetable', 'fresh',  CURRENT_DATE + 3)`
  );

  /* ---- recipes ---- */
  await pool.query(`DELETE FROM recipe_ingredients`);
  await pool.query(`DELETE FROM recipe_equipment`);
  await pool.query(`DELETE FROM recipes`);

  for (const r of recipes) {
    const result = await pool.query<{ id: number }>(
      `INSERT INTO recipes (title, description, cuisine, cooking_time, servings, difficulty, instructions)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       RETURNING id`,
      [
        r.title,
        r.description,
        r.cuisine,
        r.cooking_time,
        r.servings,
        r.difficulty,
        r.instructions,
      ]
    );

    const recipeId = result.rows[0].id;

    for (const ing of r.ingredients) {
      await pool.query(
        `INSERT INTO recipe_ingredients (recipe_id, name, quantity, unit)
         VALUES ($1, $2, $3, $4)`,
        [recipeId, ing.name, ing.quantity, ing.unit]
      );
    }

    // insert equipment
    for (const eq of r.equipment) {
      await pool.query(
        `INSERT INTO recipe_equipment (recipe_id, equipment_name) VALUES ($1, $2)`,
        [recipeId, eq]
      );
    }
  }

  // Keep seed deterministic for demos/tests
  await pool.query(`DELETE FROM favorites WHERE user_id = 1`);

  console.log(
    `Seed complete: 8 ingredients, ${recipes.length} recipes, ${recipes.reduce((n, r) => n + r.equipment.length, 0)} equipment rows inserted.`
  );
  await pool.end();
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
