import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import dotenv from "dotenv";
import bcrypt from "bcrypt";
import { pool } from "./pool.js";

dotenv.config();

const __dirname = dirname(fileURLToPath(import.meta.url));

type RecipeSeed = {
  title: string;
  description: string;
  cuisine: string;
  cooking_time: number;
  servings: number;
  difficulty: string;
  instructions: string;
  ingredients: { name: string; quantity: number; unit: string }[];
  equipment: string[];
};

type IngredientSeed = {
  name: string;
  count_quantity: number | null;
  count_unit: string | null;
  measure_quantity: number | null;
  measure_unit: string | null;
  category: string;
  status: string;
  expiry_offset: number | null;
};

const demoRecipes: RecipeSeed[] = [
  // ── 原有食譜（中文化）──────────────────────────────────────
  {
    title: "番茄炒蛋",
    description: "台灣家庭最常見的料理，滑嫩的炒蛋搭配酸甜的番茄，是每個人記憶中最熟悉的家常味道。",
    cuisine: "chinese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. 雞蛋打散加少許鹽。\n2. 番茄切丁。\n3. 熱鍋下油，炒熟雞蛋後起鍋備用。\n4. 下番茄翻炒至軟，加糖和鹽調味。\n5. 放回雞蛋拌炒均勻即可。",
    ingredients: [
      { name: "雞蛋", quantity: 3, unit: "顆" },
      { name: "番茄", quantity: 2, unit: "顆" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "糖", quantity: 1, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "菠菜煎蛋",
    description: "新鮮菠菜搭配蛋液煎製，快速又營養，是適合全年齡的健康料理。",
    cuisine: "american",
    cooking_time: 10,
    servings: 1,
    difficulty: "easy",
    instructions:
      "1. 菠菜放入熱鍋中炒軟。\n2. 雞蛋加鹽和黑胡椒打散。\n3. 將蛋液倒在菠菜上。\n4. 煎至定型後對折，盛盤即可。",
    ingredients: [
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "菠菜", quantity: 100, unit: "g" },
      { name: "鹽", quantity: 0.25, unit: "小匙" },
      { name: "奶油", quantity: 1, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "蛋炒飯",
    description: "利用剩飯製作的簡易蛋炒飯，大火快炒讓每粒米飯都裹上香氣，是台灣人的靈魂料理。",
    cuisine: "chinese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. 雞蛋打散。\n2. 熱鍋下油，炒熟雞蛋。\n3. 加入白米，大火翻炒。\n4. 加醬油和鹽調味。\n5. 撒上蔥花即可。",
    ingredients: [
      { name: "白米", quantity: 300, unit: "g" },
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "鹽", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "蒜香橄欖油義大利麵",
    description: "義大利料理中最純粹的滋味，橄欖油和蒜香賦予麵條最簡單的美味。",
    cuisine: "italian",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. 義大利麵放入加鹽的沸水中煮至彈牙。\n2. 橄欖油中加入切片大蒜和辣椒片炒香。\n3. 將麵條放入鍋中，加少許麵水拌炒。\n4. 撒上荷蘭芹即可。",
    ingredients: [
      { name: "義大利麵", quantity: 200, unit: "g" },
      { name: "大蒜", quantity: 4, unit: "瓣" },
      { name: "橄欖油", quantity: 3, unit: "大匙" },
      { name: "辣椒片", quantity: 0.5, unit: "小匙" },
      { name: "荷蘭芹", quantity: 10, unit: "g" },
      { name: "鹽", quantity: 1, unit: "小匙" },
    ],
    equipment: ["湯鍋", "平底鍋"],
  },
  {
    title: "味噌湯",
    description: "日式輕盈湯品，豆腐和海帶芽在味噌高湯中充分融合，暖胃又養生。",
    cuisine: "japanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. 高湯加熱至微滾。\n2. 加入切塊豆腐和海帶芽。\n3. 離火後溶入味噌。\n4. 盛碗後撒上蔥花即可。",
    ingredients: [
      { name: "豆腐", quantity: 150, unit: "g" },
      { name: "味噌", quantity: 2, unit: "大匙" },
      { name: "海帶芽", quantity: 5, unit: "g" },
      { name: "蔥", quantity: 1, unit: "根" },
      { name: "高湯", quantity: 500, unit: "ml" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "泡菜炒飯",
    description: "韓式泡菜的酸辣刺激與炒飯的鍋氣完美結合，頂上一顆荷包蛋，滿足感十足。",
    cuisine: "korean",
    cooking_time: 15,
    servings: 1,
    difficulty: "easy",
    instructions:
      "1. 泡菜切碎，用麻油炒香。\n2. 加入白米和泡菜汁，大火翻炒。\n3. 加醬油調味。\n4. 盛盤後放上荷包蛋，撒芝麻即可。",
    ingredients: [
      { name: "白米", quantity: 200, unit: "g" },
      { name: "泡菜", quantity: 100, unit: "g" },
      { name: "雞蛋", quantity: 1, unit: "顆" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "大匙" },
      { name: "芝麻", quantity: 1, unit: "小匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "雞肉炒時蔬",
    description: "快手家常的雞肉蔬菜拌炒，色彩鮮豔、營養均衡，是忙碌工作日的理想晚餐。",
    cuisine: "chinese",
    cooking_time: 20,
    servings: 2,
    difficulty: "medium",
    instructions:
      "1. 雞胸肉切片，用醬油和太白粉醃漬。\n2. 炒熟雞肉後起鍋備用。\n3. 依序炒香甜椒、紅蘿蔔和綠花椰菜。\n4. 放回雞肉，調味後盛盤。",
    ingredients: [
      { name: "雞胸肉", quantity: 250, unit: "g" },
      { name: "甜椒", quantity: 1, unit: "顆" },
      { name: "紅蘿蔔", quantity: 1, unit: "根" },
      { name: "綠花椰菜", quantity: 150, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "太白粉", quantity: 1, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "泰式打拋豬",
    description: "九層塔的香氣與豬絞肉在泰式調味中完美融合，辛香濃郁，蓋飯享用最過癮。",
    cuisine: "thai",
    cooking_time: 15,
    servings: 2,
    difficulty: "medium",
    instructions:
      "1. 豬肉切末或切薄片。\n2. 熱鍋下油，炒香大蒜和辣椒。\n3. 加入豬肉，炒至上色。\n4. 加醬油、蠔油和糖調味。\n5. 放入九層塔快炒，盛飯上即可。",
    ingredients: [
      { name: "豬肉", quantity: 200, unit: "g" },
      { name: "九層塔", quantity: 20, unit: "g" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "辣椒", quantity: 2, unit: "根" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "糖", quantity: 1, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
      { name: "白米", quantity: 300, unit: "g" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "奶油蘑菇義大利麵",
    description: "奶香濃郁的義大利麵，蘑菇與鮮奶油打造出滑順豐富的醬汁，是西式料理的經典。",
    cuisine: "italian",
    cooking_time: 25,
    servings: 2,
    difficulty: "medium",
    instructions:
      "1. 筆管麵放入加鹽的沸水中煮熟。\n2. 奶油下鍋，炒香蘑菇和大蒜。\n3. 加入鮮奶油和帕馬森起司，小火收汁。\n4. 放入麵條拌勻，調味後盛盤。",
    ingredients: [
      { name: "筆管麵", quantity: 200, unit: "g" },
      { name: "蘑菇", quantity: 200, unit: "g" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
      { name: "奶油", quantity: 2, unit: "大匙" },
      { name: "鮮奶油", quantity: 100, unit: "ml" },
      { name: "帕馬森起司", quantity: 30, unit: "g" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
    ],
    equipment: ["湯鍋", "平底鍋"],
  },
  {
    title: "日式咖哩飯",
    description: "雞肉、馬鈴薯、紅蘿蔔和洋蔥在咖哩塊中燉煮成濃稠醬汁，鋪在白飯上，飽足溫暖。",
    cuisine: "japanese",
    cooking_time: 45,
    servings: 4,
    difficulty: "medium",
    instructions:
      "1. 雞腿肉、馬鈴薯、紅蘿蔔、洋蔥切塊。\n2. 雞肉下油鍋煎香，加入洋蔥炒軟。\n3. 加水、馬鈴薯和紅蘿蔔，燉煮20分鐘。\n4. 加入咖哩塊拌勻至濃稠。\n5. 淋在白米飯上即可。",
    ingredients: [
      { name: "雞腿肉", quantity: 300, unit: "g" },
      { name: "馬鈴薯", quantity: 2, unit: "顆" },
      { name: "紅蘿蔔", quantity: 1, unit: "根" },
      { name: "洋蔥", quantity: 1, unit: "顆" },
      { name: "咖哩塊", quantity: 100, unit: "g" },
      { name: "白米", quantity: 400, unit: "g" },
      { name: "食用油", quantity: 1, unit: "大匙" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "三杯雞",
    description: "台灣最具代表性的家常菜，以一杯麻油、一杯醬油、一杯米酒燉煮，九層塔提香，香氣逼人。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions:
      "1. 雞腿肉切塊。\n2. 麻油熱鍋，煎至金黃。\n3. 加入薑片和大蒜炒香。\n4. 倒入醬油、米酒和糖。\n5. 燉煮至湯汁收乾。\n6. 放入九層塔快炒後盛盤。",
    ingredients: [
      { name: "雞腿肉", quantity: 400, unit: "g" },
      { name: "麻油", quantity: 3, unit: "大匙" },
      { name: "醬油", quantity: 3, unit: "大匙" },
      { name: "米酒", quantity: 3, unit: "大匙" },
      { name: "薑", quantity: 30, unit: "g" },
      { name: "大蒜", quantity: 6, unit: "瓣" },
      { name: "九層塔", quantity: 15, unit: "g" },
      { name: "糖", quantity: 1, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "牛奶法式吐司",
    description: "吐司浸入蛋奶液後煎至金黃，外酥內軟，配上楓糖漿是最幸福的早餐享受。",
    cuisine: "american",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions:
      "1. 雞蛋、牛奶和糖打散混合。\n2. 吐司浸入蛋奶液。\n3. 奶油下鍋，兩面煎至金黃。\n4. 搭配楓糖漿或蜂蜜享用。",
    ingredients: [
      { name: "吐司", quantity: 4, unit: "片" },
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "牛奶", quantity: 100, unit: "ml" },
      { name: "糖", quantity: 1, unit: "大匙" },
      { name: "奶油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  // ── 台式料理 55 道 ──────────────────────────────────────────
  {
    title: "滷肉飯",
    description: "台灣最具代表性的庶民美食，香嫩入味的五花肉燉汁澆在白飯上，令人回味無窮。",
    cuisine: "taiwanese",
    cooking_time: 60,
    servings: 4,
    difficulty: "medium",
    instructions: "1. 五花肉切小塊。\n2. 熱油將紅蔥頭炸至金黃後撈起備用。\n3. 同鍋將五花肉煎至上色。\n4. 加入醬油、米酒、糖和五香粉。\n5. 加水至剛好蓋過豬肉，小火燉煮40分鐘。\n6. 放回炸紅蔥頭繼續燉10分鐘至湯汁收稠。\n7. 盛在白米飯上即可。",
    ingredients: [
      { name: "五花肉", quantity: 400, unit: "g" },
      { name: "紅蔥頭", quantity: 5, unit: "顆" },
      { name: "醬油", quantity: 4, unit: "大匙" },
      { name: "米酒", quantity: 3, unit: "大匙" },
      { name: "糖", quantity: 1, unit: "大匙" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "白米", quantity: 400, unit: "g" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋", "湯鍋", "電鍋"],
  },
  {
    title: "麻油雞",
    description: "暖身補氣的台灣經典料理，嫩雞腿在芝麻油與米酒中慢燉，香氣四溢。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 雞腿肉切塊。\n2. 熱鍋下麻油。\n3. 薑切片下鍋，炒至稍微焦香。\n4. 加入雞肉，煎至表面金黃。\n5. 倒入米酒，大火燒開。\n6. 加入醬油，蓋鍋小火燉20分鐘。\n7. 盛盤趁熱享用。",
    ingredients: [
      { name: "雞腿肉", quantity: 500, unit: "g" },
      { name: "麻油", quantity: 3, unit: "大匙" },
      { name: "薑", quantity: 50, unit: "g" },
      { name: "米酒", quantity: 200, unit: "ml" },
      { name: "醬油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "紅燒牛肉麵",
    description: "台灣最受歡迎的麵食，牛腱在濃郁辛香的湯底中長時間燉煮，軟嫩入味。",
    cuisine: "taiwanese",
    cooking_time: 120,
    servings: 4,
    difficulty: "hard",
    instructions: "1. 牛腱汆燙後沖淨，切塊。\n2. 熱油炒香大蒜和薑，加入豆瓣醬炒出紅油。\n3. 放入牛肉，加醬油、米酒、八角和足量清水。\n4. 大火煮開後撈去浮沫，轉小火燉90分鐘至軟嫩。\n5. 另鍋將麵條煮熟。\n6. 湯底和牛肉盛在麵條上，撒蔥花即可。",
    ingredients: [
      { name: "牛腱", quantity: 600, unit: "g" },
      { name: "麵條", quantity: 400, unit: "g" },
      { name: "豆瓣醬", quantity: 2, unit: "大匙" },
      { name: "醬油", quantity: 4, unit: "大匙" },
      { name: "米酒", quantity: 3, unit: "大匙" },
      { name: "大蒜", quantity: 4, unit: "瓣" },
      { name: "薑", quantity: 30, unit: "g" },
      { name: "蔥", quantity: 3, unit: "根" },
      { name: "八角", quantity: 2, unit: "顆" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
  {
    title: "蚵仔煎",
    description: "台灣夜市必吃的招牌小吃，Q彈的地瓜粉皮裹著鮮嫩蚵仔，口感獨特。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 地瓜粉加水調成薄漿。\n2. 熱鍋下油，放入蚵仔略煎。\n3. 倒入地瓜粉漿，煎至底部定型。\n4. 雞蛋打散淋上，輕輕翻炒。\n5. 翻面煎熟。\n6. 淋上蠔油盛盤即可。",
    ingredients: [
      { name: "蚵仔", quantity: 150, unit: "g" },
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "地瓜粉", quantity: 3, unit: "大匙" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "炒米粉",
    description: "大火快炒的台式米粉，搭配豬肉與蔬菜，是台灣最受歡迎的午餐選擇之一。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 米粉用溫水泡軟後瀝乾。\n2. 豬肉、高麗菜和紅蘿蔔切絲。\n3. 熱鍋下油，炒熟豬肉。\n4. 加入高麗菜和紅蘿蔔，大火翻炒。\n5. 放入米粉、醬油和少許水。\n6. 拌炒至入味，撒蔥花即可。",
    ingredients: [
      { name: "米粉", quantity: 200, unit: "g" },
      { name: "豬肉", quantity: 150, unit: "g" },
      { name: "高麗菜", quantity: 100, unit: "g" },
      { name: "紅蘿蔔", quantity: 1, unit: "根" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "蔥油雞",
    description: "清爽鮮嫩的雞腿白切後，淋上熱騰騰的蔥油，簡單卻美味。",
    cuisine: "taiwanese",
    cooking_time: 35,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 鍋中放薑片和水煮開。\n2. 放入雞腿肉，小火煮20分鐘至熟。\n3. 撈出雞肉，冰水浸5分鐘後切片。\n4. 熱油燒至冒煙，沖入蔥段。\n5. 將蔥油淋在雞肉上。\n6. 淋上醬油即可。",
    ingredients: [
      { name: "雞腿肉", quantity: 500, unit: "g" },
      { name: "蔥", quantity: 4, unit: "根" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "食用油", quantity: 3, unit: "大匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
  {
    title: "客家小炒",
    description: "客家菜的代表作，五花肉、魷魚乾、豆腐和韭菜大火爆炒，風味濃郁。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 3,
    difficulty: "medium",
    instructions: "1. 五花肉、魷魚乾和豆腐切條。\n2. 熱油將豆腐條煎至金黃，起鍋備用。\n3. 同鍋炒五花肉至油脂滲出、邊緣微脆。\n4. 加入魷魚乾和韭菜，大火爆炒。\n5. 放回豆腐，加醬油和蠔油調味。\n6. 淋入米酒翻炒均勻即可。",
    ingredients: [
      { name: "五花肉", quantity: 150, unit: "g" },
      { name: "魷魚乾", quantity: 50, unit: "g" },
      { name: "豆腐", quantity: 200, unit: "g" },
      { name: "韭菜", quantity: 100, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "糖醋排骨",
    description: "酸甜滋味令人食指大動，炸過的排骨裹上糖醋醬，是台灣家庭的人氣菜餚。",
    cuisine: "taiwanese",
    cooking_time: 45,
    servings: 3,
    difficulty: "medium",
    instructions: "1. 排骨切4公分段，汆燙後瀝乾。\n2. 下油鍋煎至金黃。\n3. 另鍋加入白醋、糖、醬油和番茄醬煮開。\n4. 放入排骨翻炒裹醬。\n5. 燉至醬汁濃稠包裹排骨。\n6. 撒芝麻盛盤即可。",
    ingredients: [
      { name: "排骨", quantity: 500, unit: "g" },
      { name: "白醋", quantity: 3, unit: "大匙" },
      { name: "糖", quantity: 3, unit: "大匙" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "番茄醬", quantity: 2, unit: "大匙" },
      { name: "太白粉", quantity: 2, unit: "大匙" },
      { name: "芝麻", quantity: 1, unit: "小匙" },
      { name: "食用油", quantity: 3, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "紅燒五花肉",
    description: "肥而不膩的五花肉在醬油與糖的慢燉下，呈現晶瑩剔透的醬色，入口即化。",
    cuisine: "taiwanese",
    cooking_time: 90,
    servings: 4,
    difficulty: "medium",
    instructions: "1. 五花肉切大塊，汆燙5分鐘後瀝乾。\n2. 鍋中將糖炒至焦糖化，放入五花肉翻拌。\n3. 加醬油、米酒、五香粉、薑和水蓋過肉。\n4. 蓋鍋小火燉60–70分鐘至軟嫩。\n5. 開蓋大火收汁至濃稠晶亮即可。",
    ingredients: [
      { name: "五花肉", quantity: 600, unit: "g" },
      { name: "醬油", quantity: 4, unit: "大匙" },
      { name: "米酒", quantity: 3, unit: "大匙" },
      { name: "糖", quantity: 2, unit: "大匙" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "蔥", quantity: 2, unit: "根" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "清蒸魚",
    description: "最能保留魚鮮甜味的烹調方式，蒸熟後淋上醬油和蔥油，清爽鮮美。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 魚身兩面各劃幾刀。\n2. 薑片放入魚腹和魚身上。\n3. 大火蒸10–12分鐘。\n4. 倒掉蒸出的水，淋上醬油。\n5. 鋪上蔥絲。\n6. 熱油燒至冒煙，淋在蔥絲上激出香氣。\n7. 立即上桌。",
    ingredients: [
      { name: "鱸魚", quantity: 1, unit: "條" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "蔥", quantity: 3, unit: "根" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
      { name: "糖", quantity: 0.5, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "蒜炒空心菜",
    description: "大火快炒的空心菜散發焦香蒜味，是台灣餐廳必點的家常蔬菜。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 空心菜去老梗，洗淨瀝乾。\n2. 大蒜拍碎。\n3. 炒鍋大火燒熱下油。\n4. 下蒜末炒香。\n5. 放入空心菜大火快炒。\n6. 加鹽和蠔油調味，立即盛盤。",
    ingredients: [
      { name: "空心菜", quantity: 300, unit: "g" },
      { name: "大蒜", quantity: 4, unit: "瓣" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "菜脯蛋",
    description: "鹹香的菜脯與蛋汁完美結合，煎出金黃厚實的蛋餅，是台灣最質樸的家常味。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 菜脯略沖水去多餘鹽分，切碎。\n2. 雞蛋加白胡椒粉打散。\n3. 熱鍋下油，炒菜脯約1分鐘。\n4. 倒入蛋液。\n5. 底部定型後對折。\n6. 翻面煎至兩面金黃即可。",
    ingredients: [
      { name: "雞蛋", quantity: 3, unit: "顆" },
      { name: "菜脯", quantity: 40, unit: "g" },
      { name: "食用油", quantity: 2, unit: "大匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "排骨湯",
    description: "清燉排骨湯，加入白蘿蔔熬煮，湯色清澈甘甜，溫潤暖胃。",
    cuisine: "taiwanese",
    cooking_time: 50,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 排骨汆燙後沖淨。\n2. 排骨和薑放入鍋中，加足量水。\n3. 大火煮開後撈去浮沫，小火燉35分鐘。\n4. 加入白蘿蔔，再燉10分鐘。\n5. 加鹽和白胡椒粉調味。\n6. 撒蔥花盛碗即可。",
    ingredients: [
      { name: "排骨", quantity: 400, unit: "g" },
      { name: "白蘿蔔", quantity: 200, unit: "g" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "鹽", quantity: 1, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "苦瓜排骨湯",
    description: "苦瓜的清涼與排骨的鮮甜相輔相成，是台灣夏日最受歡迎的清熱湯品。",
    cuisine: "taiwanese",
    cooking_time: 50,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 排骨汆燙後瀝乾。\n2. 苦瓜對切去籽，切塊。\n3. 排骨、苦瓜和薑放入鍋中加水。\n4. 大火煮開後小火燉40分鐘。\n5. 加鹽調味即可。",
    ingredients: [
      { name: "排骨", quantity: 400, unit: "g" },
      { name: "苦瓜", quantity: 1, unit: "條" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "鹽", quantity: 1, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "紅燒豆腐",
    description: "豆腐煎至金黃後以醬汁慢燉，外皮微脆內裡軟嫩，下飯超讚。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 豆腐切厚片，用廚房紙巾吸乾水分。\n2. 熱油將豆腐兩面煎至金黃，起鍋備用。\n3. 同鍋炒香大蒜。\n4. 加醬油、蠔油、糖和少許水。\n5. 放回豆腐，小火燉至湯汁收稠。\n6. 撒蔥花盛盤即可。",
    ingredients: [
      { name: "豆腐", quantity: 300, unit: "g" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "糖", quantity: 0.5, unit: "小匙" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "食用油", quantity: 3, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "蒜炒高麗菜",
    description: "大火快炒帶出高麗菜的清甜，搭配蒜香，是台灣餐桌上最常見的家常菜。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 高麗菜剝成大片或切塊。\n2. 大蒜拍碎。\n3. 炒鍋大火燒熱下油。\n4. 下蒜末炒香。\n5. 放入高麗菜大火快炒。\n6. 加鹽和蠔油調味，立即盛盤。",
    ingredients: [
      { name: "高麗菜", quantity: 400, unit: "g" },
      { name: "大蒜", quantity: 4, unit: "瓣" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "炸排骨",
    description: "醃製入味的排骨裹上地瓜粉下油鍋炸至金黃，外酥內嫩，是便當必備菜色。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 豬排用肉鎚輕拍。\n2. 以醬油、米酒和五香粉醃漬20分鐘。\n3. 裹上地瓜粉。\n4. 入180°C油鍋炸4–5分鐘至金黃。\n5. 靜置2分鐘，搭配白米飯即可。",
    ingredients: [
      { name: "豬排", quantity: 2, unit: "片" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "地瓜粉", quantity: 4, unit: "大匙" },
      { name: "食用油", quantity: 400, unit: "ml" },
      { name: "白米", quantity: 300, unit: "g" },
    ],
    equipment: ["炒鍋", "電鍋"],
  },
  {
    title: "蚵仔麵線",
    description: "濃稠的地瓜粉勾芡湯底中有彈牙的冬粉和鮮嫩的蚵仔，是台灣街頭最暖心的小吃。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions: "1. 冬粉泡軟備用。\n2. 高湯煮開後放入蚵仔，煮約2分鐘。\n3. 加入冬粉，再煮3分鐘。\n4. 加地瓜粉水勾芡至濃稠。\n5. 加醬油和白胡椒粉調味。\n6. 淋麻油，撒香菜即可。",
    ingredients: [
      { name: "蚵仔", quantity: 150, unit: "g" },
      { name: "冬粉", quantity: 100, unit: "g" },
      { name: "地瓜粉", quantity: 3, unit: "大匙" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
      { name: "香菜", quantity: 10, unit: "g" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "蒜炒地瓜葉",
    description: "大火快炒的地瓜葉加上蒜頭，保留了蔬菜的清爽口感，是台灣常見的健康家常菜。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 地瓜葉摘除老梗，洗淨。\n2. 大蒜拍碎。\n3. 炒鍋大火燒熱下油。\n4. 下蒜末炒香。\n5. 放入地瓜葉大火快炒。\n6. 加鹽調味，炒約2分鐘即可盛盤。",
    ingredients: [
      { name: "地瓜葉", quantity: 300, unit: "g" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "蒸蛋",
    description: "滑嫩如布丁的蒸蛋，口感綿密，簡單的調味讓蛋的鮮甜完全呈現。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 雞蛋打散至均勻。\n2. 加入1.5倍的溫水混合。\n3. 加少許鹽和幾滴醬油調味。\n4. 用細篩過濾到碗中。\n5. 保鮮膜封口，小火蒸12分鐘。\n6. 起鍋後淋醬油和麻油即可。",
    ingredients: [
      { name: "雞蛋", quantity: 3, unit: "顆" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 0.5, unit: "小匙" },
      { name: "鹽", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "炒豆芽",
    description: "大火快炒保留豆芽的爽脆口感，清爽無負擔，是最簡單快速的家常小菜。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 豆芽洗淨瀝乾。\n2. 大蒜切末，蔥切段。\n3. 炒鍋大火燒熱下油。\n4. 下蒜末炒香。\n5. 放入豆芽大火快炒約2分鐘。\n6. 加鹽和米酒調味，立即盛盤。",
    ingredients: [
      { name: "豆芽菜", quantity: 300, unit: "g" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "冬瓜蛤蜊湯",
    description: "清甜的蛤蜊與鮮嫩的冬瓜搭配熬煮，湯頭清澈鮮美，清爽解膩。",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 蛤蜊泡鹽水吐沙後沖淨。\n2. 冬瓜去皮去籽，切塊。\n3. 鍋中加水和薑片煮開。\n4. 放入冬瓜，煮10分鐘至透明。\n5. 下蛤蜊，煮至殼開約3分鐘。\n6. 加鹽調味即可。",
    ingredients: [
      { name: "蛤蜊", quantity: 300, unit: "g" },
      { name: "冬瓜", quantity: 300, unit: "g" },
      { name: "薑", quantity: 15, unit: "g" },
      { name: "鹽", quantity: 0.75, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "炒茄子",
    description: "茄子煎至軟嫩後以醬汁拌炒，吸飽了蒜香與醬香，口感豐富下飯。",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 茄子切條，撒鹽靜置10分鐘。\n2. 用廚房紙巾吸乾水分。\n3. 熱油將茄子煎至軟嫩上色，起鍋備用。\n4. 同鍋炒香大蒜。\n5. 放回茄子，加醬油、蠔油和少許糖。\n6. 翻炒均勻，趁熱盛盤。",
    ingredients: [
      { name: "茄子", quantity: 2, unit: "條" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "糖", quantity: 0.5, unit: "小匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 3, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "蓮藕排骨湯",
    description: "蓮藕的清脆與排骨的鮮甜在慢燉中完美融合，湯色奶白，營養豐富。",
    cuisine: "taiwanese",
    cooking_time: 70,
    servings: 4,
    difficulty: "easy",
    instructions: "1. 排骨汆燙後瀝乾。\n2. 蓮藕去皮，切厚圓片。\n3. 排骨、蓮藕和薑放入鍋中加水。\n4. 大火煮開後撈去浮沫，小火燉60分鐘。\n5. 加鹽和白胡椒粉調味即可。",
    ingredients: [
      { name: "排骨", quantity: 400, unit: "g" },
      { name: "蓮藕", quantity: 300, unit: "g" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "鹽", quantity: 1, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "蒸肉餅",
    description: "調味好的絞肉壓成餅狀蒸熟，鮮嫩多汁，是台灣家庭餐桌上的溫馨家常菜。",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 絞肉加醬油、麻油、米酒和太白粉拌勻。\n2. 加入薑末和蔥末，混合均勻。\n3. 壓入淺碗中攤平。\n4. 中大火蒸18–20分鐘。\n5. 起鍋淋醬油，搭配白飯享用。",
    ingredients: [
      { name: "絞肉", quantity: 250, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "太白粉", quantity: 1, unit: "小匙" },
      { name: "薑", quantity: 10, unit: "g" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "白米", quantity: 300, unit: "g" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "芋頭排骨湯",
    description: "芋頭的鬆軟香甜與排骨的鮮美完美搭配，芋頭自然增稠的湯底濃郁可口。",
    cuisine: "taiwanese",
    cooking_time: 50,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 排骨汆燙後瀝乾。\n2. 芋頭去皮，切大塊。\n3. 排骨、芋頭和薑放入鍋中加水。\n4. 大火煮開後小火燉35–40分鐘至芋頭鬆軟。\n5. 加鹽調味，芋頭會自然讓湯底更濃稠。",
    ingredients: [
      { name: "排骨", quantity: 400, unit: "g" },
      { name: "芋頭", quantity: 300, unit: "g" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "鹽", quantity: 1, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "台式鹹粥",
    description: "稀飯質地綿軟，搭配豬肉末和炸紅蔥頭，是台灣早午餐的溫暖滋味。",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 白米加大量水，小火熬煮30分鐘成稀粥。\n2. 絞肉加醬油炒熟。\n3. 絞肉加入粥中拌勻。\n4. 加鹽和白胡椒粉調味。\n5. 盛碗後撒蔥花、炸紅蔥頭，淋麻油即可。",
    ingredients: [
      { name: "白米", quantity: 150, unit: "g" },
      { name: "絞肉", quantity: 100, unit: "g" },
      { name: "紅蔥頭", quantity: 3, unit: "顆" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "蝦仁炒蛋",
    description: "鮮嫩的蝦仁與滑嫩的炒蛋完美搭配，色澤漂亮，是一道簡單優雅的家常菜。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 蝦仁去腸泥，加鹽和米酒醃漬。\n2. 雞蛋加鹽打散。\n3. 熱油炒熟雞蛋至剛好定型，起鍋備用。\n4. 同鍋炒蝦仁至變色。\n5. 放回雞蛋，輕輕拌勻。\n6. 撒蔥花盛盤即可。",
    ingredients: [
      { name: "蝦仁", quantity: 200, unit: "g" },
      { name: "雞蛋", quantity: 3, unit: "顆" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "蒜苗炒肉片",
    description: "蒜苗的辛香與薄切豬肉的鮮甜完美搭配，大火快炒出鑊氣十足的美味。",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 豬肉切薄片，以醬油和太白粉醃漬。\n2. 蒜苗斜切片。\n3. 熱油炒熟豬肉，起鍋備用。\n4. 同鍋炒蒜苗至軟。\n5. 放回豬肉，加蠔油和米酒翻炒。\n6. 盛盤即可。",
    ingredients: [
      { name: "豬肉", quantity: 200, unit: "g" },
      { name: "蒜苗", quantity: 150, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "太白粉", quantity: 1, unit: "小匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "皮蛋豆腐",
    description: "嫩豆腐搭配皮蛋，淋上醬油蔥油，是台灣最受歡迎的涼拌菜，不需開火即可完成。",
    cuisine: "taiwanese",
    cooking_time: 5,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 嫩豆腐切片，排入盤中。\n2. 皮蛋切丁，散在豆腐上。\n3. 熱油燒至冒煙，沖入蔥末。\n4. 淋上醬油和蔥油。\n5. 撒芝麻即可立即享用。",
    ingredients: [
      { name: "嫩豆腐", quantity: 300, unit: "g" },
      { name: "皮蛋", quantity: 2, unit: "顆" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "芝麻", quantity: 1, unit: "小匙" },
      { name: "食用油", quantity: 1, unit: "大匙" },
    ],
    equipment: [],
  },
  {
    title: "蒜泥白肉",
    description: "水煮五花肉切薄片後淋上蒜泥醬汁，清爽不油膩，是台灣傳統的家常冷盤。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions: "1. 五花肉整塊加薑片和米酒，水煮20分鐘。\n2. 放涼後切薄片。\n3. 排入盤中，旁邊擺小黃瓜片。\n4. 蒜末、醬油、麻油和白醋調成醬汁。\n5. 將醬汁淋在肉片上。\n6. 撒蔥花即可。",
    ingredients: [
      { name: "五花肉", quantity: 400, unit: "g" },
      { name: "大蒜", quantity: 5, unit: "瓣" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "醬油", quantity: 3, unit: "大匙" },
      { name: "米酒", quantity: 2, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "大匙" },
      { name: "白醋", quantity: 1, unit: "大匙" },
      { name: "小黃瓜", quantity: 1, unit: "條" },
      { name: "蔥", quantity: 2, unit: "根" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "台式炒麵",
    description: "大火快炒的台式炒麵，麵條吸附了醬汁的鮮香，搭配豬肉和高麗菜，飽足感十足。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 麵條煮至略熟，瀝乾後拌少許油備用。\n2. 豬肉和高麗菜切絲。\n3. 熱油炒熟豬肉。\n4. 加入高麗菜，大火翻炒。\n5. 放入麵條，加醬油、蠔油和白胡椒粉。\n6. 翻炒均勻即可盛盤。",
    ingredients: [
      { name: "麵條", quantity: 200, unit: "g" },
      { name: "豬肉", quantity: 150, unit: "g" },
      { name: "高麗菜", quantity: 150, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋", "湯鍋"],
  },
  {
    title: "苦瓜釀肉",
    description: "苦瓜圈中塞入調味絞肉，煎至金黃後以醬汁燉煮，苦甘回甜的獨特風味。",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 3,
    difficulty: "medium",
    instructions: "1. 苦瓜切厚圈，挖去籽和白膜。\n2. 絞肉加醬油、麻油、薑末和太白粉拌勻。\n3. 將絞肉填入每個苦瓜圈。\n4. 熱油將兩面煎至金黃。\n5. 加少許水、醬油和蠔油。\n6. 蓋鍋燜15分鐘至絞肉熟透即可。",
    ingredients: [
      { name: "苦瓜", quantity: 1, unit: "條" },
      { name: "絞肉", quantity: 250, unit: "g" },
      { name: "醬油", quantity: 3, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "薑", quantity: 10, unit: "g" },
      { name: "太白粉", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "貢丸湯",
    description: "Q彈有勁的貢丸在清澈的高湯中煮熟，搭配高麗菜，是台灣最簡單暖胃的湯品。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 高湯小火加熱至微滾。\n2. 放入貢丸，煮約5分鐘。\n3. 加入高麗菜，再煮3分鐘。\n4. 加鹽和白胡椒粉調味。\n5. 撒蔥花，淋麻油即可。",
    ingredients: [
      { name: "貢丸", quantity: 200, unit: "g" },
      { name: "高麗菜", quantity: 150, unit: "g" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "鹽", quantity: 0.75, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "豉汁蒸排骨",
    description: "排骨以豆豉和蒜頭醃製後蒸熟，豉香濃郁，肉質軟嫩，非常下飯。",
    cuisine: "taiwanese",
    cooking_time: 35,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 排骨切小塊，沖淨拍乾。\n2. 以豆豉、大蒜、醬油、麻油、糖和太白粉醃漬20分鐘。\n3. 排入盤中，放入蒸鍋。\n4. 大火蒸20–25分鐘至熟透。\n5. 撒蔥花，搭配白米飯即可。",
    ingredients: [
      { name: "排骨", quantity: 400, unit: "g" },
      { name: "豆豉", quantity: 2, unit: "大匙" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "糖", quantity: 0.5, unit: "小匙" },
      { name: "太白粉", quantity: 1, unit: "大匙" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "白米", quantity: 300, unit: "g" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "雞排",
    description: "台灣夜市最具代表性的小吃，酥脆的外皮包裹著鮮嫩多汁的雞肉，尺寸超大令人滿足。",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 雞胸肉切開至均等厚度。\n2. 以醬油、米酒、大蒜和五香粉醃漬30分鐘。\n3. 大量裹上地瓜粉。\n4. 175°C油炸5–6分鐘至金黃熟透。\n5. 瀝油，搭配炸九層塔盛盤即可。",
    ingredients: [
      { name: "雞胸肉", quantity: 2, unit: "片" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "地瓜粉", quantity: 5, unit: "大匙" },
      { name: "九層塔", quantity: 10, unit: "g" },
      { name: "食用油", quantity: 400, unit: "ml" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "滷豬腳",
    description: "長時間燉滷的豬腳，皮Q肉嫩，膠質豐富，醬色濃亮，是台灣傳統節慶料理。",
    cuisine: "taiwanese",
    cooking_time: 120,
    servings: 4,
    difficulty: "hard",
    instructions: "1. 豬腳汆燙5分鐘後沖淨。\n2. 鍋中將糖炒至焦糖化，放入豬腳翻拌。\n3. 加醬油、米酒、五香粉、八角、薑和水蓋過豬腳。\n4. 大火煮開後小火燉90分鐘，中途翻面。\n5. 開蓋大火收汁，搭配白米飯盛盤。",
    ingredients: [
      { name: "豬腳", quantity: 1, unit: "隻" },
      { name: "醬油", quantity: 5, unit: "大匙" },
      { name: "米酒", quantity: 4, unit: "大匙" },
      { name: "糖", quantity: 2, unit: "大匙" },
      { name: "五香粉", quantity: 1, unit: "小匙" },
      { name: "八角", quantity: 3, unit: "顆" },
      { name: "薑", quantity: 30, unit: "g" },
      { name: "蔥", quantity: 3, unit: "根" },
      { name: "白米", quantity: 400, unit: "g" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "家常豆腐",
    description: "豆腐煎至金黃後加入豬絞肉和蔥花，以醬汁燜煮入味，是最受歡迎的家常菜之一。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 豆腐切塊，四面煎至金黃。\n2. 炒熟絞肉。\n3. 加入大蒜翻炒。\n4. 放回豆腐，加醬油、蠔油和少許水。\n5. 小火燜3分鐘，淋麻油。\n6. 撒蔥花即可。",
    ingredients: [
      { name: "豆腐", quantity: 300, unit: "g" },
      { name: "絞肉", quantity: 100, unit: "g" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 0.5, unit: "小匙" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "食用油", quantity: 3, unit: "大匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "薑母鴨",
    description: "老薑的辛辣與麻油的香氣完美提升鴨肉的鮮味，米酒燉煮讓肉質鮮嫩，是台灣冬令進補的首選。",
    cuisine: "taiwanese",
    cooking_time: 60,
    servings: 4,
    difficulty: "medium",
    instructions: "1. 鴨肉洗淨切塊。\n2. 麻油熱鍋，薑切片下鍋炒至稍微焦香。\n3. 放入鴨肉，大火煎至表面上色。\n4. 倒入米酒和少許水。\n5. 加醬油，蓋鍋小火燉45分鐘至軟嫩。\n6. 調整調味後盛盤。",
    ingredients: [
      { name: "鴨肉", quantity: 600, unit: "g" },
      { name: "薑", quantity: 80, unit: "g" },
      { name: "麻油", quantity: 3, unit: "大匙" },
      { name: "米酒", quantity: 200, unit: "ml" },
      { name: "醬油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "排骨麵",
    description: "酥炸豬排鋪在Q彈麵條上，搭配清甜的高湯，是台灣最受歡迎的麵食之一。",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 豬排以醬油、米酒和五香粉醃漬20分鐘。\n2. 裹地瓜粉，入180°C油鍋炸至金黃。\n3. 另起鍋，薑片和蔥加水煮成高湯，加醬油調味。\n4. 麵條另鍋煮熟，瀝乾放入碗中。\n5. 倒入熱高湯。\n6. 豬排切片鋪在麵上，撒蔥花即可。",
    ingredients: [
      { name: "豬排", quantity: 2, unit: "片" },
      { name: "麵條", quantity: 200, unit: "g" },
      { name: "醬油", quantity: 3, unit: "大匙" },
      { name: "米酒", quantity: 2, unit: "大匙" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "地瓜粉", quantity: 4, unit: "大匙" },
      { name: "薑", quantity: 15, unit: "g" },
      { name: "蔥", quantity: 3, unit: "根" },
      { name: "食用油", quantity: 400, unit: "ml" },
    ],
    equipment: ["炒鍋", "湯鍋"],
  },
  {
    title: "蘆筍炒蝦仁",
    description: "清脆的蘆筍搭配鮮嫩的蝦仁，清淡卻鮮美，是台灣家常菜中最清爽的一道。",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 蘆筍切除老梗，斜切段。\n2. 蝦仁去腸泥。\n3. 熱油炒蝦仁至變色，起鍋備用。\n4. 同鍋加大蒜，炒香後加入蘆筍翻炒至脆嫩。\n5. 放回蝦仁，加鹽和蠔油調味。\n6. 淋米酒拌炒即可盛盤。",
    ingredients: [
      { name: "蘆筍", quantity: 200, unit: "g" },
      { name: "蝦仁", quantity: 150, unit: "g" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "鹽酥雞",
    description: "台灣夜市最受歡迎的炸物，金黃酥脆的雞塊搭配九層塔，撒上胡椒鹽，令人欲罷不能。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 3,
    difficulty: "medium",
    instructions: "1. 雞腿肉切小塊。\n2. 以醬油、米酒、大蒜和五香粉醃漬20分鐘。\n3. 裹上地瓜粉。\n4. 175°C油炸至金黃酥脆。\n5. 最後1分鐘將九層塔放入油鍋略炸。\n6. 瀝油後撒白胡椒粉即可。",
    ingredients: [
      { name: "雞腿肉", quantity: 400, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "米酒", quantity: 1, unit: "大匙" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "地瓜粉", quantity: 5, unit: "大匙" },
      { name: "九層塔", quantity: 15, unit: "g" },
      { name: "白胡椒粉", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 400, unit: "ml" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "梅干扣肉",
    description: "醃漬的梅干菜與肥嫩的五花肉一同燉煮，梅干的鹹香完全滲入肉中，風味絕佳。",
    cuisine: "taiwanese",
    cooking_time: 90,
    servings: 4,
    difficulty: "hard",
    instructions: "1. 梅干菜充分沖洗後切碎。\n2. 五花肉切厚片。\n3. 熱油將紅蔥頭炸香。\n4. 放入五花肉煎至上色。\n5. 加梅干菜、醬油、米酒和糖。\n6. 加水蓋過，小火燉70分鐘。\n7. 開蓋大火收汁即可。",
    ingredients: [
      { name: "五花肉", quantity: 500, unit: "g" },
      { name: "梅干菜", quantity: 150, unit: "g" },
      { name: "紅蔥頭", quantity: 4, unit: "顆" },
      { name: "醬油", quantity: 4, unit: "大匙" },
      { name: "米酒", quantity: 3, unit: "大匙" },
      { name: "糖", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
  {
    title: "滷蛋",
    description: "在醬油和五香的鹵汁中慢慢浸煮的雞蛋，蛋白呈現深褐色，入味又美味。",
    cuisine: "taiwanese",
    cooking_time: 40,
    servings: 4,
    difficulty: "easy",
    instructions: "1. 雞蛋煮熟後剝殼，表面輕劃幾刀。\n2. 鍋中加醬油、茶包、五香粉、糖和水。\n3. 放入雞蛋，煮開後小火燉25分鐘。\n4. 關火後讓雞蛋繼續浸泡至少10分鐘。\n5. 切半後盛盤，溫熱或常溫皆可享用。",
    ingredients: [
      { name: "雞蛋", quantity: 6, unit: "顆" },
      { name: "醬油", quantity: 4, unit: "大匙" },
      { name: "五香粉", quantity: 1, unit: "小匙" },
      { name: "糖", quantity: 1, unit: "大匙" },
      { name: "茶包", quantity: 2, unit: "包" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "台式蛋花湯",
    description: "雞蛋緩緩倒入沸騰的湯中形成絲絲蛋花，加上番茄的酸甜，清爽好喝。",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 高湯煮開後加鹽調味。\n2. 太白粉加水調勻，倒入鍋中攪拌至微稠。\n3. 雞蛋打散，慢慢沿鍋緣倒入，同時攪拌形成蛋花。\n4. 放入番茄角。\n5. 加白胡椒粉，淋麻油。\n6. 撒蔥花盛碗即可。",
    ingredients: [
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "番茄", quantity: 1, unit: "顆" },
      { name: "太白粉", quantity: 1, unit: "大匙" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "麻油", quantity: 0.5, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
      { name: "鹽", quantity: 0.75, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "肉燥麵",
    description: "鮮香的絞肉肉燥澆在Q彈麵條上，搭配滷蛋，是台灣最具代表性的便民午餐。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 麵條煮至彈牙後瀝乾。\n2. 炒熟絞肉。\n3. 加醬油、米酒、糖和五香粉，小火燉10分鐘。\n4. 放入炸紅蔥頭拌勻。\n5. 肉燥淋在麵條上。\n6. 放上滷蛋，撒蔥花即可。",
    ingredients: [
      { name: "麵條", quantity: 200, unit: "g" },
      { name: "絞肉", quantity: 200, unit: "g" },
      { name: "紅蔥頭", quantity: 3, unit: "顆" },
      { name: "醬油", quantity: 3, unit: "大匙" },
      { name: "米酒", quantity: 2, unit: "大匙" },
      { name: "糖", quantity: 1, unit: "小匙" },
      { name: "五香粉", quantity: 0.5, unit: "小匙" },
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "食用油", quantity: 1, unit: "大匙" },
    ],
    equipment: ["炒鍋", "湯鍋"],
  },
  {
    title: "豆腐清湯",
    description: "清爽的高湯搭配嫩豆腐和蘑菇，調味簡單卻鮮美，滋補而不油膩。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 豆腐切塊。\n2. 高湯加薑片煮開。\n3. 放入豆腐和蘑菇，小火煮5分鐘。\n4. 加入蔥段。\n5. 加鹽、白胡椒粉和麻油調味。\n6. 盛碗趁熱享用。",
    ingredients: [
      { name: "豆腐", quantity: 300, unit: "g" },
      { name: "蘑菇", quantity: 100, unit: "g" },
      { name: "薑", quantity: 10, unit: "g" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "麻油", quantity: 0.5, unit: "小匙" },
      { name: "鹽", quantity: 0.75, unit: "小匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "炒金針菇",
    description: "金針菇大火快炒搭配蒜頭和蔥花，口感爽脆，是最快速的家常小菜之一。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 金針菇切除根部，撥散成小束。\n2. 大蒜切末，蔥切段。\n3. 熱油中火炒香蒜末。\n4. 放入金針菇，大火翻炒約2分鐘。\n5. 加醬油和蠔油調味即可盛盤。",
    ingredients: [
      { name: "金針菇", quantity: 200, unit: "g" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
      { name: "蔥", quantity: 2, unit: "根" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "滷雞翅",
    description: "雞翅以醬油和米酒慢燉至入味，表面晶亮有光澤，是老少皆宜的美味菜餚。",
    cuisine: "taiwanese",
    cooking_time: 35,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 雞翅洗淨拍乾。\n2. 熱油將雞翅四面煎至金黃。\n3. 加大蒜和薑，略炒。\n4. 加醬油、米酒、糖和水至半淹。\n5. 小火燉25分鐘，中途翻面。\n6. 大火收汁即可盛盤。",
    ingredients: [
      { name: "雞翅", quantity: 500, unit: "g" },
      { name: "醬油", quantity: 3, unit: "大匙" },
      { name: "米酒", quantity: 2, unit: "大匙" },
      { name: "糖", quantity: 1, unit: "大匙" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "薑", quantity: 15, unit: "g" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "蔥油餅",
    description: "手工製作的蔥油餅層層酥脆，蔥香四溢，是台灣最受歡迎的早點之一。",
    cuisine: "taiwanese",
    cooking_time: 30,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 中筋麵粉加沸水和鹽揉成光滑麵團，靜置20分鐘。\n2. 擀薄後刷上食用油，撒蔥花。\n3. 緊緊捲成條狀，再盤成圓形。\n4. 再次擀平。\n5. 中火入油鍋，兩面煎至金黃酥脆。",
    ingredients: [
      { name: "中筋麵粉", quantity: 200, unit: "g" },
      { name: "蔥", quantity: 4, unit: "根" },
      { name: "食用油", quantity: 3, unit: "大匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "酸菜炒肉絲",
    description: "鹹酸的酸菜與嫩滑的肉絲一同拌炒，酸鹹開胃，是極佳的下飯菜。",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 酸菜充分沖水後擠乾，切碎。\n2. 豬肉切絲，以醬油和太白粉醃漬。\n3. 熱油炒熟豬肉絲，起鍋備用。\n4. 同鍋炒香酸菜、大蒜和辣椒。\n5. 放回豬肉絲，拌炒均勻，搭配白飯即可。",
    ingredients: [
      { name: "豬肉", quantity: 200, unit: "g" },
      { name: "酸菜", quantity: 150, unit: "g" },
      { name: "大蒜", quantity: 2, unit: "瓣" },
      { name: "辣椒", quantity: 1, unit: "根" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "太白粉", quantity: 1, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "豆腐蔬菜火鍋",
    description: "豆腐、蘑菇與各式蔬菜在清甜的高湯中熬煮，暖身又健康。",
    cuisine: "taiwanese",
    cooking_time: 25,
    servings: 3,
    difficulty: "easy",
    instructions: "1. 高湯加薑片煮開。\n2. 放入豆腐、蘑菇和高麗菜。\n3. 小火燉10分鐘。\n4. 加入菠菜，再煮2分鐘。\n5. 加鹽、醬油和麻油調味。\n6. 直接端鍋上桌享用。",
    ingredients: [
      { name: "豆腐", quantity: 300, unit: "g" },
      { name: "蘑菇", quantity: 150, unit: "g" },
      { name: "高麗菜", quantity: 200, unit: "g" },
      { name: "菠菜", quantity: 100, unit: "g" },
      { name: "薑", quantity: 15, unit: "g" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 1, unit: "小匙" },
      { name: "鹽", quantity: 0.75, unit: "小匙" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "炒豬肝",
    description: "豬肝切薄片後以大火快炒，搭配薑和蔥，保留鮮嫩口感，富含鐵質。",
    cuisine: "taiwanese",
    cooking_time: 15,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 豬肝切薄片，浸水10分鐘後瀝乾。\n2. 以米酒和醬油醃漬。\n3. 炒鍋大火燒熱下油。\n4. 下薑片略炒。\n5. 放入豬肝，大火快炒2–3分鐘，切勿過熟。\n6. 加蔥段、蠔油和麻油，翻炒盛盤。",
    ingredients: [
      { name: "豬肝", quantity: 250, unit: "g" },
      { name: "薑", quantity: 20, unit: "g" },
      { name: "蔥", quantity: 3, unit: "根" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "米酒", quantity: 2, unit: "大匙" },
      { name: "蠔油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "鳳梨炒飯",
    description: "甜蜜的鳳梨塊與鮮嫩蝦仁在白飯中拌炒，搭配腰果增添口感，是台灣特色炒飯。",
    cuisine: "taiwanese",
    cooking_time: 20,
    servings: 2,
    difficulty: "medium",
    instructions: "1. 白米提前煮好放涼。\n2. 熱油炒蝦仁至變色，起鍋備用。\n3. 同鍋炒散雞蛋，加入白米大火翻炒。\n4. 加入鳳梨塊、腰果和醬油。\n5. 放回蝦仁，加鹽和白胡椒粉調味即可。",
    ingredients: [
      { name: "白米", quantity: 300, unit: "g" },
      { name: "蝦仁", quantity: 150, unit: "g" },
      { name: "雞蛋", quantity: 2, unit: "顆" },
      { name: "鳳梨", quantity: 150, unit: "g" },
      { name: "腰果", quantity: 30, unit: "g" },
      { name: "醬油", quantity: 2, unit: "大匙" },
      { name: "白胡椒粉", quantity: 0.25, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
    ],
    equipment: ["炒鍋", "電鍋"],
  },
  {
    title: "蒜油菠菜",
    description: "菠菜燙熟後淋上熱蒜油，簡單調味即呈現清爽鮮美，是最健康的家常蔬菜。",
    cuisine: "taiwanese",
    cooking_time: 10,
    servings: 2,
    difficulty: "easy",
    instructions: "1. 菠菜放入加鹽的沸水中汆燙1分鐘。\n2. 撈出瀝乾，輕輕擠去多餘水分。\n3. 熱油炒香蒜末至金黃。\n4. 將蒜油淋在菠菜上。\n5. 加醬油和麻油拌勻即可。",
    ingredients: [
      { name: "菠菜", quantity: 300, unit: "g" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "醬油", quantity: 1, unit: "大匙" },
      { name: "麻油", quantity: 0.5, unit: "小匙" },
      { name: "食用油", quantity: 2, unit: "大匙" },
      { name: "鹽", quantity: 0.5, unit: "小匙" },
    ],
    equipment: ["湯鍋", "炒鍋"],
  },
];

const demoIngredients: IngredientSeed[] = [
  { name: "Milk",      count_quantity: null, count_unit: null, measure_quantity: 1,   measure_unit: "L",  category: "dairy",     status: "opened", expiry_offset: 2   },
  { name: "Eggs",      count_quantity: 12,   count_unit: "顆", measure_quantity: null, measure_unit: null, category: "dairy",     status: "fresh",  expiry_offset: 10  },
  { name: "Spinach",   count_quantity: null, count_unit: null, measure_quantity: 200, measure_unit: "g",  category: "vegetable", status: "fresh",  expiry_offset: -1  },
  { name: "Rice",      count_quantity: null, count_unit: null, measure_quantity: 500, measure_unit: "g",  category: "grain",     status: "fresh",  expiry_offset: null },
  { name: "Soy Sauce", count_quantity: 1,    count_unit: "包", measure_quantity: null, measure_unit: null, category: "condiment", status: "opened", expiry_offset: 90  },
  { name: "Garlic",    count_quantity: 5,    count_unit: "顆", measure_quantity: null, measure_unit: null, category: "vegetable", status: "fresh",  expiry_offset: 14  },
  { name: "Butter",    count_quantity: null, count_unit: null, measure_quantity: 100, measure_unit: "g",  category: "dairy",     status: "fresh",  expiry_offset: 30  },
  { name: "Tomatoes",  count_quantity: 3,    count_unit: "顆", measure_quantity: null, measure_unit: null, category: "vegetable", status: "fresh",  expiry_offset: 3   },
];

// ─── Alice — 台日料理愛好者 ──────────────────────────────────────────────────

const aliceRecipes: RecipeSeed[] = [
  {
    title: "三杯雞",
    description: "台式經典，麻油、醬油、米酒各一杯，香氣四溢。",
    cuisine: "taiwanese", cooking_time: 30, servings: 3, difficulty: "medium",
    instructions: "1. 雞腿切塊備用。\n2. 熱鍋下麻油，爆香薑片和蒜頭。\n3. 放入雞塊煎至表面金黃。\n4. 加入醬油、米酒、糖，大火燒開後轉小火燜煮。\n5. 收汁後加入九層塔翻炒即可。",
    ingredients: [
      { name: "雞腿", quantity: 400, unit: "g" },
      { name: "麻油", quantity: 3, unit: "tbsp" },
      { name: "醬油", quantity: 3, unit: "tbsp" },
      { name: "米酒", quantity: 3, unit: "tbsp" },
      { name: "薑", quantity: 30, unit: "g" },
      { name: "蒜頭", quantity: 6, unit: "顆" },
      { name: "九層塔", quantity: 15, unit: "g" },
      { name: "糖", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
  {
    title: "味噌豆腐湯",
    description: "清淡暖胃的日式湯品，豆腐嫩滑、味噌香濃。",
    cuisine: "japanese", cooking_time: 10, servings: 2, difficulty: "easy",
    instructions: "1. 昆布高湯煮滾。\n2. 放入切丁豆腐和裙帶菜。\n3. 關火後溶入味噌。\n4. 撒上蔥花即可上桌。",
    ingredients: [
      { name: "豆腐", quantity: 200, unit: "g" },
      { name: "味噌", quantity: 2, unit: "tbsp" },
      { name: "裙帶菜", quantity: 5, unit: "g" },
      { name: "蔥", quantity: 1, unit: "根" },
      { name: "昆布高湯", quantity: 500, unit: "ml" },
    ],
    equipment: ["湯鍋"],
  },
  {
    title: "滷肉飯",
    description: "肥瘦相間的豬五花慢滷入味，拌飯一流。",
    cuisine: "taiwanese", cooking_time: 60, servings: 4, difficulty: "medium",
    instructions: "1. 五花肉切小丁，油蔥酥炒香。\n2. 加入醬油、冰糖、米酒和水。\n3. 滷包放入，小火燉煮 40 分鐘。\n4. 盛飯，淋上滷肉即可。",
    ingredients: [
      { name: "豬五花", quantity: 400, unit: "g" },
      { name: "醬油", quantity: 4, unit: "tbsp" },
      { name: "米酒", quantity: 2, unit: "tbsp" },
      { name: "冰糖", quantity: 1, unit: "tbsp" },
      { name: "油蔥酥", quantity: 2, unit: "tbsp" },
      { name: "白飯", quantity: 600, unit: "g" },
      { name: "水", quantity: 200, unit: "ml" },
    ],
    equipment: ["湯鍋", "電鍋"],
  },
  {
    title: "玉子燒",
    description: "日式甜味煎蛋捲，早餐便當必備。",
    cuisine: "japanese", cooking_time: 15, servings: 2, difficulty: "easy",
    instructions: "1. 雞蛋打散，加入味醂、醬油、砂糖拌勻。\n2. 玉子燒鍋塗油熱鍋。\n3. 倒入少量蛋液，半凝固時捲起推至一端。\n4. 重複加蛋液捲疊，共三至四層即完成。",
    ingredients: [
      { name: "雞蛋", quantity: 3, unit: "顆" },
      { name: "味醂", quantity: 1, unit: "tbsp" },
      { name: "醬油", quantity: 0.5, unit: "tsp" },
      { name: "砂糖", quantity: 1, unit: "tsp" },
      { name: "食用油", quantity: 1, unit: "tsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "蔥爆豬肉",
    description: "大蔥與豬肉的完美組合，下飯首選。",
    cuisine: "taiwanese", cooking_time: 15, servings: 2, difficulty: "easy",
    instructions: "1. 豬肉片用醬油、米酒醃 10 分鐘。\n2. 熱鍋大火快炒豬肉至變色盛起。\n3. 原鍋炒香蒜末，放入大蔥段翻炒。\n4. 豬肉回鍋，加蠔油調味炒勻即可。",
    ingredients: [
      { name: "豬肉片", quantity: 250, unit: "g" },
      { name: "大蔥", quantity: 2, unit: "根" },
      { name: "蒜頭", quantity: 3, unit: "顆" },
      { name: "醬油", quantity: 2, unit: "tbsp" },
      { name: "米酒", quantity: 1, unit: "tbsp" },
      { name: "蠔油", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["炒鍋"],
  },
];

const aliceIngredients: IngredientSeed[] = [
  { name: "雞腿",   count_quantity: 2,    count_unit: "塊", measure_quantity: null, measure_unit: null, category: "meat",      status: "fresh",  expiry_offset: 2   },
  { name: "豆腐",   count_quantity: null, count_unit: null, measure_quantity: 300, measure_unit: "g",  category: "other",     status: "fresh",  expiry_offset: 3   },
  { name: "味噌",   count_quantity: null, count_unit: null, measure_quantity: 200, measure_unit: "g",  category: "condiment", status: "opened", expiry_offset: 60  },
  { name: "白飯",   count_quantity: null, count_unit: null, measure_quantity: 600, measure_unit: "g",  category: "grain",     status: "fresh",  expiry_offset: 1   },
  { name: "蔥",     count_quantity: 3,    count_unit: "根", measure_quantity: null, measure_unit: null, category: "vegetable", status: "fresh",  expiry_offset: 4   },
  { name: "薑",     count_quantity: null, count_unit: null, measure_quantity: 50,  measure_unit: "g",  category: "vegetable", status: "fresh",  expiry_offset: 14  },
  { name: "醬油",   count_quantity: 1,    count_unit: "瓶", measure_quantity: null, measure_unit: null, category: "condiment", status: "opened", expiry_offset: 180 },
  { name: "麻油",   count_quantity: null, count_unit: null, measure_quantity: 100, measure_unit: "ml", category: "condiment", status: "opened", expiry_offset: 180 },
  { name: "雞蛋",   count_quantity: 6,    count_unit: "顆", measure_quantity: null, measure_unit: null, category: "dairy",     status: "fresh",  expiry_offset: 14  },
  { name: "豬五花", count_quantity: null, count_unit: null, measure_quantity: 400, measure_unit: "g",  category: "meat",      status: "fresh",  expiry_offset: 2   },
];

// ─── Bob — 西式料理愛好者（已全中文化） ─────────────────────────────────────────

const bobRecipes: RecipeSeed[] = [
  {
    title: "培根蛋波納拉義大利麵",
    description: "經典羅馬義大利麵，搭配香脆培根、蛋黃與起司。",
    cuisine: "italian", cooking_time: 20, servings: 2, difficulty: "medium",
    instructions: "1. 義大利麵放入鹽水中煮至保有口感。\n2. 培根煎至香脆後撈出備用。\n3. 將蛋黃、帕馬森起司與黑胡椒攪拌均勻。\n4. 關火，利用餘溫將熱麵條與蛋黃醬汁拌勻。\n5. 加入培根與少許煮麵水調整濃稠度，立即上桌。",
    ingredients: [
      { name: "義大利麵", quantity: 200, unit: "g" },
      { name: "培根", quantity: 100, unit: "g" },
      { name: "蛋黃", quantity: 3, unit: "個" },
      { name: "帕馬森起司", quantity: 50, unit: "g" },
      { name: "黑胡椒", quantity: 1, unit: "tsp" },
      { name: "鹽", quantity: 1, unit: "tsp" },
    ],
    equipment: ["湯鍋", "平底鍋"],
  },
  {
    title: "BLT 三明治",
    description: "香脆培根、鮮美萵苣與多汁番茄的經典組合。",
    cuisine: "american", cooking_time: 10, servings: 1, difficulty: "easy",
    instructions: "1. 吐司烤至金黃酥脆。\n2. 培根煎至香脆。\n3. 在兩片吐司上塗抹美乃滋。\n4. 依序鋪上萵苣、番茄和培根。\n5. 對切後即可享用。",
    ingredients: [
      { name: "吐司", quantity: 2, unit: "片" },
      { name: "培根", quantity: 60, unit: "g" },
      { name: "萵苣", quantity: 30, unit: "g" },
      { name: "番茄", quantity: 1, unit: "個" },
      { name: "美乃滋", quantity: 1, unit: "tbsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "經典牛肉堡",
    description: "鮮美多汁的手工牛肉漢堡排搭配經典配料。",
    cuisine: "american", cooking_time: 20, servings: 2, difficulty: "medium",
    instructions: "1. 牛絞肉加入鹽 and 黑胡椒拌勻，拍打塑形成漢堡排。\n2. 煎鍋或烤盤每面煎 3-4 分鐘。\n3. 烤熱漢堡麵包。\n4. 依序放上萵苣、番茄、起司片、漢堡肉與醬料組裝。",
    ingredients: [
      { name: "牛絞肉", quantity: 300, unit: "g" },
      { name: "漢堡麵包", quantity: 2, unit: "個" },
      { name: "切達起司", quantity: 2, unit: "片" },
      { name: "萵苣", quantity: 40, unit: "g" },
      { name: "番茄", quantity: 1, unit: "個" },
      { name: "洋蔥", quantity: 0.5, unit: "個" },
      { name: "鹽", quantity: 0.5, unit: "tsp" },
      { name: "黑胡椒", quantity: 0.5, unit: "tsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "美式培根炒蛋",
    description: "奶香濃郁的滑嫩炒蛋搭配香脆培根條。",
    cuisine: "american", cooking_time: 10, servings: 1, difficulty: "easy",
    instructions: "1. 雞蛋與少許牛奶、調味料一同打散。\n2. 培根煎至香脆後撈出備用。\n3. 小火在鍋中融化奶油。\n4. 倒入蛋液並輕柔推動翻褶，至半熟凝固即可。\n5. 與培根一同擺盤上桌。",
    ingredients: [
      { name: "雞蛋", quantity: 3, unit: "顆" },
      { name: "培根", quantity: 80, unit: "g" },
      { name: "奶油", quantity: 1, unit: "tbsp" },
      { name: "牛奶", quantity: 2, unit: "tbsp" },
      { name: "鹽", quantity: 0.25, unit: "tsp" },
      { name: "黑胡椒", quantity: 0.25, unit: "tsp" },
    ],
    equipment: ["平底鍋"],
  },
  {
    title: "番茄羅勒義大利麵",
    description: "新鮮番茄醬汁搭配羅勒與大蒜的清爽義大利麵。",
    cuisine: "italian", cooking_time: 25, servings: 2, difficulty: "easy",
    instructions: "1. 橄欖油熱鍋，爆香蒜碎。\n2. 加入切丁番茄，小火燉煮 15 分鐘至軟爛。\n3. 加入鹽調味並撒入撕碎的羅勒葉。\n4. 放入煮好的義大利麵一同翻炒，最後撒上帕馬森起司。",
    ingredients: [
      { name: "義大利麵", quantity: 200, unit: "g" },
      { name: "番茄", quantity: 3, unit: "個" },
      { name: "大蒜", quantity: 3, unit: "瓣" },
      { name: "橄欖油", quantity: 3, unit: "tbsp" },
      { name: "羅勒", quantity: 10, unit: "g" },
      { name: "帕馬森起司", quantity: 30, unit: "g" },
      { name: "鹽", quantity: 1, unit: "tsp" },
    ],
    equipment: ["湯鍋", "平底鍋"],
  },
];

const bobIngredients: IngredientSeed[] = [
  { name: "培根",       count_quantity: null, count_unit: null, measure_quantity: 200, measure_unit: "g",      category: "meat",      status: "fresh",  expiry_offset: 5   },
  { name: "雞蛋",       count_quantity: 6,    count_unit: "顆", measure_quantity: null, measure_unit: null, category: "dairy",     status: "fresh",  expiry_offset: 14  },
  { name: "義大利麵",   count_quantity: null, count_unit: null, measure_quantity: 500, measure_unit: "g",      category: "grain",     status: "fresh",  expiry_offset: null },
  { name: "帕馬森起司", count_quantity: null, count_unit: null, measure_quantity: 100, measure_unit: "g",      category: "dairy",     status: "opened", expiry_offset: 30  },
  { name: "奶油",       count_quantity: null, count_unit: null, measure_quantity: 200, measure_unit: "g",      category: "dairy",     status: "fresh",  expiry_offset: 30  },
  { name: "牛奶",       count_quantity: null, count_unit: null, measure_quantity: 1,   measure_unit: "L",      category: "dairy",     status: "opened", expiry_offset: 4   },
  { name: "番茄",       count_quantity: 4,    count_unit: "顆", measure_quantity: null, measure_unit: null, category: "vegetable", status: "fresh",  expiry_offset: 3   },
  { name: "萵苣",       count_quantity: null, count_unit: null, measure_quantity: 150, measure_unit: "g",      category: "vegetable", status: "fresh",  expiry_offset: 2   },
  { name: "大蒜",       count_quantity: 4,    count_unit: "瓣", measure_quantity: null, measure_unit: null, category: "vegetable", status: "fresh",  expiry_offset: 14  },
  { name: "橄欖油",     count_quantity: null, count_unit: null, measure_quantity: 300, measure_unit: "ml",     category: "condiment", status: "opened", expiry_offset: 365 },
  { name: "吐司",       count_quantity: 6,    count_unit: "片", measure_quantity: null, measure_unit: null, category: "grain",     status: "fresh",  expiry_offset: 3   },
];

// ─── Helpers ─────────────────────────────────────────────────────────────────

async function upsertUser(email: string, displayName: string, password: string): Promise<string> {
  const hash = await bcrypt.hash(password, 10);
  const result = await pool.query<{ id: string }>(
    `INSERT INTO users (email, display_name, password_hash)
     VALUES ($1, $2, $3)
     ON CONFLICT (email) DO UPDATE SET password_hash = EXCLUDED.password_hash, display_name = EXCLUDED.display_name
     RETURNING id`,
    [email, displayName, hash]
  );
  return result.rows[0].id;
}

async function seedIngredients(userId: string, items: IngredientSeed[]) {
  await pool.query(`DELETE FROM ingredients WHERE user_id = $1`, [userId]);
  for (const item of items) {
    const expiry = item.expiry_offset !== null
      ? `CURRENT_DATE + ${item.expiry_offset}`
      : "NULL";
    await pool.query(
      `INSERT INTO ingredients (user_id, name, count_quantity, count_unit, measure_quantity, measure_unit, category, status, expiry_date)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, ${expiry})`,
      [userId, item.name, item.count_quantity, item.count_unit, item.measure_quantity, item.measure_unit, item.category, item.status]
    );
  }
}

async function seedRecipes(userId: string, recipeList: RecipeSeed[]) {
  await pool.query(`DELETE FROM recipe_ingredients WHERE recipe_id IN (SELECT id FROM recipes WHERE user_id = $1)`, [userId]);
  await pool.query(`DELETE FROM recipe_equipment   WHERE recipe_id IN (SELECT id FROM recipes WHERE user_id = $1)`, [userId]);
  await pool.query(`DELETE FROM recipes WHERE user_id = $1`, [userId]);

  for (const r of recipeList) {
    const result = await pool.query<{ id: number }>(
      `INSERT INTO recipes (user_id, title, description, cuisine, cooking_time, servings, difficulty, instructions)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id`,
      [userId, r.title, r.description, r.cuisine, r.cooking_time, r.servings, r.difficulty, r.instructions]
    );
    const recipeId = result.rows[0].id;
    for (const ing of r.ingredients) {
      await pool.query(
        `INSERT INTO recipe_ingredients (recipe_id, name, quantity, unit) VALUES ($1, $2, $3, $4)`,
        [recipeId, ing.name, ing.quantity, ing.unit]
      );
    }

    for (const eq of r.equipment) {
      await pool.query(
        `INSERT INTO recipe_equipment (recipe_id, equipment_name) VALUES ($1, $2)`,
        [recipeId, eq]
      );
    }
  }
}

// ─── Main ─────────────────────────────────────────────────────────────────────

async function seed() {
  const schema = readFileSync(join(__dirname, "schema.sql"), "utf-8");
  await pool.query(schema);

  const users = [
    { email: "demo@example.com",  display_name: "測試帳號",        password: "demo1234",  recipes: demoRecipes,  ingredients: demoIngredients  },
    { email: "alice@example.com", display_name: "Alice（台日料理）", password: "alice1234", recipes: aliceRecipes, ingredients: aliceIngredients },
    { email: "bob@example.com",   display_name: "Bob（西式料理）",   password: "bob12345",  recipes: bobRecipes,   ingredients: bobIngredients   },
  ];

  for (const u of users) {
    const userId = await upsertUser(u.email, u.display_name, u.password);
    await seedIngredients(userId, u.ingredients);
    await seedRecipes(userId, u.recipes);
    await pool.query(`DELETE FROM favorites WHERE user_id = $1`, [userId]);
    console.log(`  ✓ ${u.email} (${u.display_name}) — ${u.ingredients.length} 項食材, ${u.recipes.length} 道食譜資料已匯入`);
  }

  console.log("\nSeed 完成！範例帳號：");
  for (const u of users) {
    console.log(`  ${u.email} / ${u.password}`);
  }
  await pool.end();
}

seed().catch((e) => {
  console.error(e);
  process.exit(1);
});
